### PR TITLE
Add ls alias to store list

### PR DESCRIPTION
**Pull request by luxifer**
## Description

This PR implements feature request in #540

## Motivation and Context

As stated in the issue, this PR aims to improve UX.

## How Has This Been Tested?

I ran `faas-cli store ls` locally.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Thanks for your first PR :100: This change looks relatively harmless so not sure we need to do any extensive testing on it. Maybe you could just provide the console output of ls and list to show they both work? 

Alex

**Comment by luxifer** [comment]
```
$ ./faas-cli store list

FUNCTION                    DESCRIPTION
Colorization                Turn black and white photos to color ...
Inception                   This is a forked version of the work ...
Have I Been Pwned           The Have I Been Pwned function lets y...
SSL/TLS cert info           Returns SSL/TLS certificate informati...
Face Detection with Pigo    Detect faces in images using the Pigo...
SentimentAnalysis           Python function provides a rating on ...
Figlet                      OpenFaaS Figlet image. This repositor...
NodeInfo                    Get info about the machine that you'r...
Tesseract OCR               This function brings OCR - Optical Ch...
Dockerhub Stats             Golang function gives the count of re...
QR Code Generator - Go      QR Code generator using Go
Nmap Security Scanner       Tool for network discovery and securi...
ASCII Cows                  Generate cartoons of ASCII cows
YouTube Video Downloader    Download YouTube videos as a function
OpenFaaS Text-to-Speech     Generate an MP3 of text using Google'...
nslookup                    Uses nslookup to return any IP addres...
Docker Image Manifest Query Query an image on the Docker Hub for ...
face-detect with OpenCV     Detect faces in images. Send a URL as...
Left-Pad                    left-pad on OpenFaaS
mememachine                 Turn any image into a meme.

$ ./faas-cli store ls

FUNCTION                    DESCRIPTION
Colorization                Turn black and white photos to color ...
Inception                   This is a forked version of the work ...
Have I Been Pwned           The Have I Been Pwned function lets y...
SSL/TLS cert info           Returns SSL/TLS certificate informati...
Face Detection with Pigo    Detect faces in images using the Pigo...
SentimentAnalysis           Python function provides a rating on ...
Figlet                      OpenFaaS Figlet image. This repositor...
NodeInfo                    Get info about the machine that you'r...
Tesseract OCR               This function brings OCR - Optical Ch...
Dockerhub Stats             Golang function gives the count of re...
QR Code Generator - Go      QR Code generator using Go
Nmap Security Scanner       Tool for network discovery and securi...
ASCII Cows                  Generate cartoons of ASCII cows
YouTube Video Downloader    Download YouTube videos as a function
OpenFaaS Text-to-Speech     Generate an MP3 of text using Google'...
nslookup                    Uses nslookup to return any IP addres...
Docker Image Manifest Query Query an image on the Docker Hub for ...
face-detect with OpenCV     Detect faces in images. Send a URL as...
Left-Pad                    left-pad on OpenFaaS
mememachine                 Turn any image into a meme.
```

**Comment by ivanayov** [comment]
Looks good 💯 I tried it too.

Good first contribution @luxifer 👍

**Comment by luxifer** [comment]
Thank you!

**Comment by rgee0** [comment]
Derek set milestone: 0.7.6

**Pull request merged**
