### PR TITLE
Added ability to include annotations in template.yml for inclusion in…

### PR DESCRIPTION
**Pull request by whitmell**
Added ability to include annotations in template.yml for inclusion in function.yml on new command

Signed-off-by: Whit Matthews <whitmell@gmail.com>

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by whitmell** [comment]
@alexellis  I thought I'd try my hand at working the feature request I added yesterday.  I'm new to golang though so please let me know if I missed anything.  Thanks!

**Comment by alexellis** [comment]
Sorry this issue was not approved or discussed yet. The contributing guide needs approval from a maintainer before changes are submitted. This is quite common, the Docker project uses the same standards.

**Comment by whitmell** [comment]
Understood.  Is there any action needed from me at the moment or do I just need to wait until it's discussed and approved?

**Comment by alexellis** [comment]
Hey Whit, we are going to need an issue creating for this.

Let's close the PR, we can always reopen it after a discussion.

I also haven't heard back from you or your colleague on the email thread you started with us, can you take a look please?

Alex

**Pull request closed without merging**
