### PR TITLE
Add --tls-no-verify to commands

### PR DESCRIPTION
**Pull request by affix**
From Issue #376 add a --tls-no-verify flag

## Description
Adds a --tls-no-verify flag to commands. This defaults to false to that TLS/SSL certificates must be valid.

Append the --tls-no-verify flag to your command to skip TLS/SSL Verification.

## Motivation and Context
solves issue #376

## How Has This Been Tested?
Tested manually agains my faas-nettes setup with an nginx proxy

**Valid SSL**
- Can Login Successfuly without --tls-no-verify  :white_check_mark:
- Can Login Successfuly with --tls-no-verify :white_check_mark:
- Can Deploy Successfuly without --tls-no-verify :white_check_mark:
- Can Deploy Successfuly with --tls-no-verify :white_check_mark:
- Can List Successfuly without --tls-no-verify :white_check_mark:
- Can List Successfuly with --tls-no-verify :white_check_mark:
- Can Invoke Successfuly without --tls-no-verify :white_check_mark:
- Can Invoke Successfuly with --tls-no-verify :white_check_mark:

**No SSL**
- Can Login Successfuly without --tls-no-verify :white_check_mark:
- Can Login Successfuly with --tls-no-verify :white_check_mark:
- Can Deploy Successfuly without --tls-no-verify :white_check_mark:
- Can Deploy Successfuly with --tls-no-verify :white_check_mark:
- Can List Successfuly without --tls-no-verify :white_check_mark:
- Can List Successfuly with --tls-no-verify :white_check_mark:
- Can Invoke Successfuly without --tls-no-verify :white_check_mark:
- Can Invoke Successfuly with --tls-no-verify :white_check_mark:

**Invalud SSL**
- Can Not Login Successfuly without --tls-no-verify :white_check_mark: 
- Can Login Successfuly with --tls-no-verify :white_check_mark:
- Can Not Deploy Successfuly without --tls-no-verify :white_check_mark:
- Can Deploy Successfuly with --tls-no-verify :white_check_mark:
- Can Not List Successfuly without --tls-no-verify :white_check_mark:
- Can List Successfuly with --tls-no-verify :white_check_mark:
- Can Not Invoke Successfuly without --tls-no-verify :white_check_mark:
- Can Invoke Successfuly with --tls-no-verify :white_check_mark:

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Hi,

CI is failing (probably due to gofmt.. )and your commits should probably be squashed since I don’t think they add value being separated out. 

Please provide details of your positive, negative and no harm testing: HTTPS valid, https invalid and http.

**Comment by Affix** [comment]
Will provide details and fix failing CI today

**Comment by Affix** [comment]
@alexellis Its still failing because I made proxy changes, I have added my test cases

**Comment by alexellis** [comment]
Are you sure it's not due to gofmt? That is the line I saw fail. How about running ./build_redist.sh locally?

**Comment by Affix** [comment]
```
# github.com/openfaas/faas-cli/commands
commands/store.go:48:32: not enough arguments in call to proxy.MakeHTTPClient
	have (*time.Duration)
	want (*time.Duration, bool)
FAIL	github.com/openfaas/faas-cli [build failed]
# github.com/openfaas/faas-cli/proxy
proxy/deploy_test.go:33:17: not enough arguments in call to DeployFunction
	have (string, string, string, string, string, string, bool, nil, string, []string, bool, []string, map[string]string, FunctionResourceRequest)
	want (string, string, string, string, string, string, bool, map[string]string, string, []string, bool, []string, map[string]string, FunctionResourceRequest, bool)
proxy/deploy_test.go:92:17: not enough arguments in call to DeployFunction
	have (string, string, string, string, string, string, bool, nil, string, []string, bool, []string, map[string]string, FunctionResourceRequest)
	want (string, string, string, string, string, string, bool, map[string]string, string, []string, bool, []string, map[string]string, FunctionResourceRequest, bool)
proxy/invoke_test.go:22:26: not enough arguments in call to InvokeFunction
	have (string, string, *[]byte, string, []string, []string, bool, string)
	want (string, string, *[]byte, string, []string, []string, bool, string, bool)
proxy/invoke_test.go:43:26: not enough arguments in call to InvokeFunction
	have (string, string, *[]byte, string, []string, []string, bool, string)
	want (string, string, *[]byte, string, []string, []string, bool, string, bool)
proxy/invoke_test.go:64:26: not enough arguments in call to InvokeFunction
	have (string, string, *[]byte, string, []string, []string, bool, string)
	want (string, string, *[]byte, string, []string, []string, bool, string, bool)
proxy/invoke_test.go:88:26: not enough arguments in call to InvokeFunction
	have (string, string, *[]byte, string, []string, []string, bool, string)
	want (string, string, *[]byte, string, []string, []string, bool, string, bool)
proxy/list_test.go:26:30: not enough arguments in call to ListFunctions
	have (string)
	want (string, bool)
proxy/list_test.go:41:25: not enough arguments in call to ListFunctions
	have (string)
	want (string, bool)
proxy/list_test.go:54:25: not enough arguments in call to ListFunctions
	have (string)
	want (string, bool)
# github.com/openfaas/faas-cli/commands
/tmp/go-build042462476/github.com/openfaas/faas-cli/commands/_test/_obj_test/store.go:50:32: not enough arguments in call to proxy.MakeHTTPClient
	have (*time.Duration)
	want (*time.Duration, bool)
ok  	github.com/openfaas/faas-cli/builder	0.007s	coverage: 37.7% of statements
FAIL	github.com/openfaas/faas-cli/commands [build failed]
ok  	github.com/openfaas/faas-cli/config	0.015s	coverage: 81.0% of statements
FAIL	github.com/openfaas/faas-cli/proxy [build failed]
?   	github.com/openfaas/faas-cli/sample/github_hmac	[no test files]
?   	github.com/openfaas/faas-cli/schema	[no test files]
ok  	github.com/openfaas/faas-cli/stack	0.035s	coverage: 54.3% of statements
?   	github.com/openfaas/faas-cli/test	[no test files]
ok  	github.com/openfaas/faas-cli/version	0.001s	coverage: 100.0% of statements
?   	github.com/openfaas/faas-cli/versioncontrol	[no test files]
```

@alexellis

**Comment by alexellis** [comment]
Hi @Affix thanks for updating the description with your testing. Please can you fix the CI build/test error or whatever is going wrong with it currently?

**Comment by Affix** [comment]
@alexellis Its due to the missing changes to proxy in the repo I beleive and these will pass after merge

```
# github.com/openfaas/faas-cli/proxy
proxy/deploy_test.go:33:17: not enough arguments in call to DeployFunction
	have (string, string, string, string, string, string, bool, nil, string, []string, bool, []string, map[string]string, FunctionResourceRequest)
	want (string, string, string, string, string, string, bool, map[string]string, string, []string, bool, []string, map[string]string, FunctionResourceRequest, bool)
proxy/deploy_test.go:92:17: not enough arguments in call to DeployFunction
	have (string, string, string, string, string, string, bool, nil, string, []string, bool, []string, map[string]string, FunctionResourceRequest)
	want (string, string, string, string, string, string, bool, map[string]string, string, []string, bool, []string, map[string]string, FunctionResourceRequest, bool)
proxy/invoke_test.go:22:26: not enough arguments in call to InvokeFunction
	have (string, string, *[]byte, string, []string, []string, bool, string)
	want (string, string, *[]byte, string, []string, []string, bool, string, bool)
proxy/invoke_test.go:43:26: not enough arguments in call to InvokeFunction
	have (string, string, *[]byte, string, []string, []string, bool, string)
	want (string, string, *[]byte, string, []string, []string, bool, string, bool)
proxy/invoke_test.go:64:26: not enough arguments in call to InvokeFunction
	have (string, string, *[]byte, string, []string, []string, bool, string)
	want (string, string, *[]byte, string, []string, []string, bool, string, bool)
proxy/invoke_test.go:88:26: not enough arguments in call to InvokeFunction
	have (string, string, *[]byte, string, []string, []string, bool, string)
	want (string, string, *[]byte, string, []string, []string, bool, string, bool)
proxy/list_test.go:26:30: not enough arguments in call to ListFunctions
	have (string)
	want (string, bool)
proxy/list_test.go:41:25: not enough arguments in call to ListFunctions
	have (string)
	want (string, bool)
proxy/list_test.go:54:25: not enough arguments in call to ListFunctions
	have (string)
	want (string, bool)
# github.com/openfaas/faas-cli/commands
commands/store.go:48:32: not enough arguments in call to proxy.MakeHTTPClient
	have (*time.Duration)
	want (*time.Duration, bool)
```

**Comment by alexellis** [comment]
@Affix I checked out your PR on my local machine and `./build.sh` fails to complete with the above test errors

The only reason I could think that your code would build locally and fail on CI is if there was a vendored package which needed to be updated, but no faas-cli packages are vendored by the faas-cli.

Merging your PR wouldn't fix anything - it would break the codebase. The errors I'm seeing are due to the change in the signature of `DeployFunction` / `InvokeFunction`. Try this locally:

```
go test ./proxy/
```

**Comment by Affix** [comment]
thans @alexellis fixed the tests :)

**Comment by alexellis** [comment]
What was wrong? I suspect that if this code was broken locally then the tests will be giving false information.

**Comment by Affix** [comment]
When I sqaushed the commits something went wrong, I had some local changes and had a bit of a merge conflict

**Comment by BurtonR** [comment]
@Affix Almost there, but looks like there's a conflict now in the proxy/deploy. Could you do a rebase and fix the conflict?
Then, we can mark this as ready for testing and have some others check it out and run through some tests. Thanks!

**Comment by affix** [comment]
@BurtonR Rebased with Upstream and resolved the conflict :)

**Comment by alexellis** [comment]
> This branch cannot be rebased due to conflicts

Please can you rebase and also see comments.

**Comment by alexellis** [comment]
Awaiting review from @johnmccabe 

I think that this could be merged, it does need a rebase though. @affix I know you're away for a while on vacation, we may be able to do that for you and retain the Git author, but not sure about the Git commit-er.

Alex

**Comment by alexellis** [comment]
Merged in #460.

Alex

**Pull request closed without merging**
