### PR TITLE
Added the ability to run get.sh as non-root user

### LINKED ISSUE #247: Let utility script run as non-root
Let utility script run as non-root

I.e. 

This should download to current folder:

```
curl -sL cli.openfaas.com | sh
```

If non-root we should print out sudo instructions:

```
sudo cp faas-cli /usr/local/bin/
sudo ln -s /usr/local/bin/{faas-cli,faas}
```

This should download to /usr/local/bin/

```
curl -sL cli.openfaas.com | sudo sh
```

### PR DESCRIPTION
**Pull request by rgee0**
Signed-off-by: rgee0 <richard@technologee.co.uk>

## Description
Fixes #247 Let utility script run as non-root

## Motivation and Context
Users may be less comfortable running a remotely sourced script as root.  This change enables users to run the cli get script as a non-root user and instructs them as to the next steps to be performed in order to complete installation.

- [x] I have raised an issue to propose this change (#247)

## How Has This Been Tested?

Ran with and without sudo, thus:

```
$ cd ~
$ cat /tmp/get.sh | sudo sh

You already have the faas-cli!
Overwriting in 1 seconds.. Press Control+C to cancel.

Downloading package https://github.com/openfaas/faas-cli/releases/download/0.5.0/faas-cli-darwin as /tmp/faas-cli
Download complete.

Running as root - Attemping to move faas-cli to /usr/local/bin
New version of faas-cli installed to /usr/local/bin
```
And
```
$ cd ~
$ cat /tmp/get.sh | sh

You already have the faas-cli!
Overwriting in 1 seconds.. Press Control+C to cancel.

Downloading package https://github.com/openfaas/faas-cli/releases/download/0.5.0/faas-cli-darwin as /Users/rgee0/faas-cli
Download complete.

====================================================
== As the script was run as a non-root user the   ==
== following commands may need to be run manually ==
====================================================

     sudo cp faas-cli /usr/local/bin/
     sudo ln -s /usr/local/bin/{faas-cli,faas}
```
## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Excellent work 👍 Very speedy. Can we get a couple of people to verify it then I can deploy to the server.

**Comment by austinfrey** [comment]
I'm getting this output when running the updated script.

using `sudo`
```
$ cat /tmp/get.sh | sudo sh
You already have the faas-cli!
Overwriting in 1 seconds.. Press Control+C to cancel.

x86_64
sh: 50: [: Illegal number: 
Downloading package https://github.com/openfaas/faas-cli/releases/download/0.5.0/faas-cli as /tmp/faas-cli
Download complete.
sh: 69: [: Illegal number: 

Running as root - Attemping to move faas-cli to /usr/local/bin
New version of faas-cli installed to /usr/local/bin
Creating alias 'faas' for 'faas-cli'.
```

not using `sudo`
```
$ cat /tmp/get.sh | sh
You already have the faas-cli!
Overwriting in 1 seconds.. Press Control+C to cancel.

x86_64
sh: 50: [: Illegal number: 
rm: cannot remove '/tmp/faas-cli': Operation not permitted
Downloading package https://github.com/openfaas/faas-cli/releases/download/0.5.0/faas-cli as /tmp/faas-cli
sh: 61: cannot create /tmp/faas-cli: Permission denied
```

**Comment by austinfrey** [comment]
New changes worked for non root worked for me. I do get some errors when executing as root though if I've already installed as non-root. Both outputs below. 
```
$ cat /tmp/get.sh | sh
You already have the faas-cli!
Overwriting in 1 seconds.. Press Control+C to cancel.

x86_64
Downloading package https://github.com/openfaas/faas-cli/releases/download/0.5.0/faas-cli as /home/austin/faas-cli
Download complete.

====================================================
== As the script was run as a non-root user the   ==
== following commands may need to be run manually ==
====================================================

     sudo cp faas-cli /usr/local/bin/
     sudo ln -s /usr/local/bin/{faas-cli,faas}
```

as root
```
$ cat /tmp/get.sh | sudo sh
You already have the faas-cli!
Overwriting in 1 seconds.. Press Control+C to cancel.

x86_64
Downloading package https://github.com/openfaas/faas-cli/releases/download/0.5.0/faas-cli as /tmp/faas-cli
Download complete.

Running as root - Attemping to move faas-cli to /usr/local/bin
New version of faas-cli installed to /usr/local/bin
ln: failed to create symbolic link './{faas-cli,faas}': File exists
Creating alias 'faas' for 'faas-cli'.
```

**Comment by rgee0** [comment]
@austinfrey thanks for testing, really appreciate it.  I've only recently (last couple of days) got myself an ubuntu box so had only really tested on mac.

the latest commit should address the issues highlighted through testing on ubuntu.

**Comment by austinfrey** [comment]
Both root and non-root methods now execute appropriately on Ubuntu 16+ for me. Output below.
with `sudo`
```
x86_64
Downloading package https://github.com/openfaas/faas-cli/releases/download/0.5.0/faas-cli as /tmp/faas-cli
Download complete.

Running as root - Attemping to move faas-cli to /usr/local/bin
New version of faas-cli installed to /usr/local/bin
```
without `sudo`
```
x86_64
Downloading package https://github.com/openfaas/faas-cli/releases/download/0.5.0/faas-cli as /home/austin/faas-cli
Download complete.

=========================================================
==    As the script was run as a non-root user the     ==
==    following commands may need to be run manually   ==
=========================================================

  sudo cp faas-cli /usr/local/bin/
  sudo ln -s /usr/local/bin/faas-cli /usr/local/bin/faas
```

**Comment by rgee0** [comment]
Also now tested on a pi3.  Both modes were successful.

Added `-f` to `ln` commad in the non-root output to suppress the message if a user tries to create when it already exists.

**Comment by alexellis** [comment]
Merged. Thanks @rgee0

**Pull request merged**
