### PR TITLE
Update struct for OpenFaaS Function store

### LINKED ISSUE #792: faas-cli generate - cannot unmarshal object into Go value of type []schema.StoreItem
## Expected Behaviour

The following should generate an operator CRD for me to apply with ` | kubectl apply -f -`
```
faas-cli generate --from-store nodeinfo
```

## Current Behaviour

```
Unable to retrieve functions from URL https://raw.githubusercontent.com/openfaas/store/master/functions.json: cannot parse result from OpenFaaS store at URL: https://raw.githubusercontent.com/openfaas/store/master/functions.json
json: cannot unmarshal object into Go value of type []schema.StoreItem
```

## Steps to Reproduce (for bugs)

```
faas-cli generate --from-store nodeinfo
Unable to retrieve functions from URL https://raw.githubusercontent.com/openfaas/store/master/functions.json: cannot parse result from OpenFaaS store at URL: https://raw.githubusercontent.com/openfaas/store/master/functions.json
json: cannot unmarshal object into Go value of type []schema.StoreItem
```

## Context

Expected feature for Operator / CRD users as per docs at: https://github.com/openfaas/openfaas-operator

### PR DESCRIPTION
**Pull request by Waterdrips**
## Description

Looks like the store json is different to the expected structure in the
cli for generating the yaml spec from the function store definitions.
There was a missing wrapper sruct that took the version and the list of
functions.

This has been tested with go build && ./faas-cli generate --from-store
nodeinfo

This generated yaml when there was an error before

Signed-off-by: Alistair Hey <alistair@heyal.co.uk>

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))
Fixes #792 

## How Has This Been Tested?

This has been tested with go build && ./faas-cli generate --from-store
nodeinfo

This generated yaml when there was an error before

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by Waterdrips** [comment]
https://github.com/openfaas/store/commit/1a39d34b1f8991366b076ce0d8802fa6390164f8#diff-39dce271af4b77f29f47fd2d5a3bdc41 Looks like this commit broke the structure we expected in the CLI. I havn't verified that by crossrefing anything here, its just a quick search

**Comment by alexellis** [comment]
This shows that we are not testing the command in CI. Please could you add a test to run this command and to ensure it exits with 0?

**Comment by alexellis** [comment]
We have some examples of how to do this for example: https://github.com/openfaas/faas-cli/blob/1f121592a943a4d3d7545231e18f5c1e1f72bc31/commands/remove_test.go

**Comment by Waterdrips** [comment]
Sure, will do

**Comment by alexellis** [comment]
Thanks, ping me when ready.

**Comment by Waterdrips** [comment]
@alexellis this commit removed "image" and replaced it with "images"
https://github.com/openfaas/store/commit/b37bf8c067319ac7fcdd502afeddce0ee6ed0167#diff-39dce271af4b77f29f47fd2d5a3bdc41

This means the spec doesn't match the cli's struct, and we now don't know which image version to use when using the `faas-cli generate --from-store nodeinfo` 

Should we default to x86_64 then allow override with a flag?

**Comment by alexellis** [comment]
Yes sounds good. Look at the faas store list command that gained the platform flag

**Comment by Waterdrips** [comment]
just finalising changes:

If a user puts an arch that doesnt exist it will print options: 

```
go build && ./faas-cli generate --from-store nodeinfo --arch amd64
Image for amd64 not found in store. 
options: [arm64 armhf x86_64]
```

Default is `x86_64`

And success: 

```
go build && ./faas-cli generate --from-store nodeinfo
---
apiVersion: openfaas.com/v1alpha2
kind: Function
metadata:
  name: nodeinfo
spec:
  name: nodeinfo
  image: functions/nodeinfo-http:latest
  labels: {}

```

**Comment by Waterdrips** [comment]
@alexellis - this should be good to review now.

**Comment by alexellis** [comment]
@Waterdrips, can you confirm why CI is failing?

**Comment by alexellis** [comment]
Screenshot 2020-04-23 at 16 02 05

**Comment by alexellis** [comment]
Thanks for that.

**Pull request merged**
