### PR TITLE
Enable passing query string parameters when using invoke

### PR DESCRIPTION
**Pull request by nenadilic84**
Signed-off-by: Nenad Ilic <nenadilic84@gmail.com>

## Description

New parameter `query` is added to the `invoke` command to allow passing query strings
## Motivation and Context

It implements the issue #168 

## How Has This Been Tested?

```
faas-cli invoke flaskapp --query name=test
```

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Hi @nenadilic84 - thanks for your first contribution. I didn't know you were working on this. It is pretty close to what I wrote on the plane over to Dockercon in #173. Let's merge one of the versions but also add unit tests so that we can regression test this and combine the best of both approaches?

Can you add some tests to your PR and have a look at the ones already out there for inspiration?

**Comment by nenadilic84** [comment]
You are welcome 😄. I'll do the merge and add the unit tests...

**Comment by nenadilic84** [comment]
@alexellis, I've updated the PR. Let me know if it's this what you had in mind...

**Comment by alexellis** [comment]
Please can you retro-fit your tests to #173 if that makes sense? Once CI passes I'll merge and if there is an opportunity to add coverage let's do it.

**Pull request closed without merging**
