### PR TITLE
Add flag to control trimming of secrets

### LINKED ISSUE #859: faas-cli secret create corrupts the secret when there is a whitespace at the end
In my specific case, I wanted to create OpenSSH private keys, but this is a general issue.
SSH private keys MUST have a new line at the end, but the `faas-cli secret create` command trims the secret value.

This is the problematic line, it should be simply removed: https://github.com/openfaas/faas-cli/blob/356b9130018debcce7ef291843e5c3247c07c7f9/commands/secret_create.go#L102

### PR DESCRIPTION
**Pull request by LucasRoesler**
## Description

- Add flag `--trim` with default value `true`. This allows the user to
  control if whitespace is trimmed from the start and end of the secret
  value. This can be useful if the secret values format requires
  trailing newlines. The default value of `true` preserves backwards
  compatibility

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))
Resolves #859

## How Has This Been Tested?

Manually tested locally

```sh
➜  ~ kind create cluster
# output omitted
➜  ~ arkade install openfaas -a=false
# output omitted
➜  ~ faas-cli secret create foo
Reading from STDIN - hit (Control + D) to stop.
a
b
c

WARNING! Communication is not secure, please consider using HTTPS. Letsencrypt.org offers free SSL/TLS certificates.
Creating secret: foo
Created: 202 Accepted

➜  ~ kubectl get secret -n openfaas-fn foo -o jsonpath="{.data.foo}" | base64 --decode
a
b
c% 

➜  ~ faas-cli secret create bar --trim=false
Reading from STDIN - hit (Control + D) to stop.
a
b
c



WARNING! Communication is not secure, please consider using HTTPS. Letsencrypt.org offers free SSL/TLS certificates.
Creating secret: bar
Created: 202 Accepted
➜  ~ kubectl get secret -n openfaas-fn bar -o jsonpath="{.data.bar}" | base64 --decode
a
b
c


➜  ~
```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by LucasRoesler** [comment]
@kissgyorgy perhaps you would be willing to help do a second verification of this?

**Review by alexellis — APPROVED** [review]
Approved

**Comment by alexellis** [comment]
The pre-release binary will be available at: https://github.com/openfaas/faas-cli/releases/tag/0.13.1

Thanks for working on the PR @LucasRoesler

**Comment by kissgyorgy** [comment]
Nice, thanks!
This will work, although I still think a `trim=true` default would be better, but I understand the backward compatibility requirement. 👍

**Comment by alexellis** [comment]
We never used to trim the text, then someone said it was a bug that it didn't trim, so we added trim by default.

Now someone else has said that trimming is a bug.

I guess you can see the difficulty and why we try to be more objective? 😄 

Glad you are pleased with the result, if you're not already sponsoring the openfaas community, take a look at https://github.com/sponsors/openfaas/

**Pull request merged**
