### PR TITLE
Updated `faas-cli new` to print welcome message

### PR DESCRIPTION
**Pull request by viveksyngh**
This commit updates `faas-cli new` command to print language specific
welcome message by default. It also has a flag `--quiet` or `-q` to
supress the welcome message.

Fixes: #437

Signed-off-by: Vivek Singh <vivekkmr45@yahoo.in>

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))
Issue raised by @alexellis #437 

## How Has This Been Tested?

I have tested this on my local for the following scenario. 
 1. For a template with the welcome message 

```
openfaas /Users/viveks/Repos/go-projects/src/github.com/openfaas/faas-cli/faas-cli new demo1 --lang=go                           
Folder: demo1 created.
  ___                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|


Function created in folder: demo1
Stack file written: demo1.yml

Notes:
You have created a new function which uses Golang 1.9.7.
To include third-party dependencies, use a vendoring tool like dep:
dep documentation: https://github.com/golang/dep#installation

➜  openfaas /Users/viveks/Repos/go-projects/src/github.com/openfaas/faas-cli/faas-cli new demo2 --lang=go --append=demo1.yml 
Folder: demo2 created.
  ___                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|


Function created in folder: demo2
Stack file updated: demo1.yml

Notes:
You have created a new function which uses Golang 1.9.7.
To include third-party dependencies, use a vendoring tool like dep:
dep documentation: https://github.com/golang/dep#installation
```

2. For a template with the welcome message with `--quiet` flag

```
➜  openfaas /Users/viveks/Repos/go-projects/src/github.com/openfaas/faas-cli/faas-cli new demo3 --lang=go --append=demo1.yml --quiet
Folder: demo3 created.
  ___                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|


Function created in folder: demo3
Stack file updated: demo1.yml
➜  openfaas /Users/viveks/Repos/go-projects/src/github.com/openfaas/faas-cli/faas-cli new demo4 --lang=go --append=demo1.yml -q     
Folder: demo4 created.
  ___                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|


Function created in folder: demo4
Stack file updated: demo1.yml
```
3. For a template without welcome message.

```
/Users/viveks/Repos/go-projects/src/github.com/openfaas/faas-cli/faas-cli new demo5 --lang=node --append=demo1.yml  
Folder: demo5 created.
  ___                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|


Function created in folder: demo5
Stack file updated: demo1.yml
```
`template.yml`

```yaml
language: go
fprocess: ./handler
welcome: |
    You have created a new function which uses Golang 1.9.7.
    To include third-party dependencies, use a vendoring tool like dep:
    dep documentation: https://github.com/golang/dep#installation

```

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by viveksyngh** [comment]
@alexellis I have incorporated the review changes and pushed it.

**Comment by viveksyngh** [comment]
I have started adding messages to templates. Might need your help on that.

**Comment by alexellis** [comment]
LGTM

**Comment by alexellis** [comment]
Derek set milestone: 0.6.14

**Pull request merged**
