### PR TITLE
Add consistent ARM64 build image process

### PR DESCRIPTION
**Pull request by rdimitrov**
Signed-off-by: Radoslav Dimitrov <rdimitrow@gmail.com>

## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Derek reviewer: ewilde

**Comment by alexellis** [comment]
Derek set reviewer: ewilde

**Comment by rdimitrov** [comment]
For .PHONY, decided to make it consistent to the other Makefiles where it's used as a single line other than stating it before every make option. If you want I can discard that changes?

**Comment by alexellis** [comment]
Requested input from @ewilde ... will merge this change since there are a lot of similar ones.

**Comment by ewilde** [comment]
@alexellis @rdimitrov the idea of having a phony target before each target is really down to maintenance. 

- It's easier to check if you are missing a phony
- You get less merge problems. Single line will get more contention

 easier to check

**Comment by rdimitrov** [comment]
Updated the use of .PHONY targets based on the feedback - https://github.com/openfaas/faas-cli/pull/574

**Pull request merged**
