### PR TITLE
[WIP] Accomodate spaces in --build-arg value

### LINKED ISSUE #392: Build returns "docker build" requires exactly 1 argument with particular build-arg values
When passing a build-arg value that contains newlines, the docker build step fails with `ERROR - Could not execute command`

A practical example is to pass to the CLI the expansion of an environment variable containing a private key.

```
> export DEPLOY_KEY=$(cat ~/.ssh/private_key_rsa)
> faas-cli build my-function --build-arg DEPLOY_KEY="$DEPLOY_KEY"
```

This will fail, and even worse, will echo the private key to the screen.

## Expected Behaviour

CLI should gracefully handle quoted multiline strings as input to build-arg without causing the `docker build` to error out due to encountering more arguments than expected.

## Current Behaviour

CLI invokes `docker build` in such a way as to treat newlines as argument separators even when the value passed to build-arg quoted.

## Possible Solution

This might just be a case of not adequately escaping the flags before adding them to the command to be executed, but I'm not familiar with the intricacies of Go's mechanism for calling shell commands to say for certain.  I do know that running the raw docker command from my own shell behaves as expected.  A working image can be built by running:

```
cd ./build/my-function && docker build --build-arg DEPLOY_KEY="$DEPLOY_KEY" -t user/repo:tag .
```

I'm also not certain how to guard against echoing the contents of the env var to screen (or to a log in CI) if the exec from go fails due to the contents of the env var or for any other reason.

## Steps to Reproduce (for bugs)

1. `export MY_MULTILINE_ARG=$(cat any_file_with_newlines)`
2. `faas-cli build my-function --build-arg TEST_ARG="$MY_MULTILINE_ARG"`
3. The docker command will fail because it interprets anything after a newline as a new argument despite the presence of quotes before and after the passed argument's contents.

## Context

I'm trying to build functions that rely on packages from a private repo, and doing so requires the presence of a private key in the docker context.  A quick and repeatable way to accomplish this is to place the key into an environment variable to be passed as a build arg.  My custom build template takes care of all of that just fine, but it can't be called through `faas-cli build` due to this bug.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
```
  ___                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|

Commit: ae7390005a2fe13873f2cb6fcfa2d830dad4a40b
Version: 0.6.5
```

* Docker version ( Full output from: `docker version` ):
```
Client:
 Version:      17.09.0-ce
 API version:  1.23
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.12.1-ce
 API version:  1.35 (minimum version 1.12)
 Go version:   go1.9.4
 Git commit:   7390fc6
 Built:        Tue Feb 27 22:20:43 2018
 OS/Arch:      linux/amd64
 Experimental: false
```

* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?
Kubernetes

* Operating System and version (e.g. Linux, Windows, MacOS):
macOS 10.12.6

### PR DESCRIPTION
**Pull request by rgee0**
Signed-off-by: rgee0 <richard@technologee.co.uk>

## Description
With the recent addition of --build-arg no provision for the potential for spaces
was made.  This was a problem as the slice that is passed into exec.command() was being
generated via a strings.Split() on space which meant values with spaces were split
across slice elements.

This change alters this behaviour by returning a slice of strings from the buildFlag function
which obviates the need for string.Split further downstream and so removes the potential for
mis-handling of spaces.

## Motivation and Context

- [x] I have raised an issue to propose this change (fixes #392)

## How Has This Been Tested?
Much of the testing so far was performed through debugging the issue.
Added a test for the changed method `buildFlagSlice`

### Test method to exercise original issue:
* Export a variable containing a private key
* Amend the relevant template Dockerfile to accept an `ARG` and add `ARG DEPLOY_KEY=${DEPLOY_KEY}`
* Run the build - `./faas-cli-darwin build hello-python --build-arg DEPLOY_KEY="$DEPLOY_KEY" -f hello-python.yml`
* Run the resulting image `docker run -ti hello-python:latest /bin/sh`
* Inside the container check `env` for existence of `DEPLOY_KEY`

**Further testing is required, particularly by third parties.**

Seeking feedback on approach.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by rgee0** [comment]
cc: @ryanfields

**Comment by rgee0** [comment]
Unit test added for `buildFlagSlice`

**Comment by ryanfields** [comment]
@rgee0 Just gave this a test and my functions built without issue, so this fix looks good.  Thank you.

**Comment by alexellis** [comment]
I like that this fixes the issue, adds unit test coverage with scenarios and is documented in the commit as to why slices are used. Is there a way we can also document the use of slices over strings in the code (through naming?) so that someone doesn't convert it back one day?

**Comment by rgee0** [comment]
Variable names amended to try to better convey purpose.

**Comment by alexellis** [comment]
Please remove WIP if this is ready to merge.

**Pull request merged**
