### PR TITLE
Add external Docker registry authentication support via arguments/YAML

### LINKED ISSUE #22: CLI should support private registries
Private registries are supported by the FaaS REST API - https://github.com/alexellis/faas/blob/master/docs/managing-images.md

The support hasn't been added to the CLI / YAML yet.

### PR DESCRIPTION
**Pull request by burtonr**
Signed-off-by: Nenad Ilic <nenadilic84@gmail.com>
Signed-off-by: Burton Rheutan <rheutan7@gmail.com>

Changes from @nenadilic84  on PR #181 
I only did a rebase and corrected conflicts

## Description
An additional argument has been added in order to pass information to the FaaS gateway in order to authenticate the docker client.

## Motivation and Context

- [X] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

Resolves #22 
More info: https://github.com/openfaas/faas/blob/master/docs/managing-images.md

## How Has This Been Tested?

Testing performed on previous PR

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [X] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by BurtonR** [comment]
@alexellis  @johnmccabe  @stefanprodan 
This is the rebase/merge of the previous PR with the same name.

I'm having trouble with it pulling images from my private Azure Container Registry: `burtonr.azurecr.io`
It _looks like_ the `github.com/docker/distribution/reference` doesn't like having `.` in the name... 

I'll try to fire up another private registry somewhere without the `.`, but in the meantime, could someone try this out to make sure I didn't break anything in the rebase? There were a lot of changes since this was last worked!

Thanks!

**Comment by alexellis** [comment]
Hey Burton, how about trying with the Docker Hub and a private repo there? What part is unhappy? Thr client or the server code?

**Comment by BurtonR** [comment]
Ok, so I've finally figured out what the issue was I was having... I was using a tag on the `image` which breaks as we are using the `withName()` function for `faas-swarm`...  I suppose we'll need to do another PR there to allow passing a tag with the image name

Also, in my personal private registry, I wasn't using user/repo names which was another issue. I had `burtonr.azurecr.io/test-fn`, but needed to re-tag to use `burtonr.azurecr.io/burtonr/test-fn`

So, finally, I can say this **does work** as expected. I tested with both a private `hub.docker.com` repo as well as a private registry. Both deployed to a PWD swarm (to guarantee that the login wasn't there) and verified that both functions were invoke-able. 

@alexellis or @johnmccabe  Could you verify that this also works with the Mac "keychain" similar to the Docker CLI? I don't have a Mac to test that with. Thanks!

**Comment by alexellis** [comment]
Great progress on this. Do we need a patch to faas-swarm?

**Comment by BurtonR** [comment]
Here's the issue I opened over in faas-swarm: https://github.com/openfaas/faas-swarm/issues/19

**Comment by alexking** [comment]
Regarding this working on a Mac via keychain, I've been able to successfully use it on macOS 10.13.4 deploying an image from a private docker hub repository. Thanks for the work on this, it's very useful 👍

**Comment by alexellis** [comment]
Let's get a test on:
- [ ] Linux
- [ ] Mac
- [ ] Windows

**Pull request merged**
