### PR TITLE
Link to cli.openfaas.com repo

### LINKED ISSUE #586: Add instructions for updating get.sh
## Expected Behaviour

There should be a note in the contributing guide saying that the `get.sh` file is served from https://github.com/openfaas/cli.openfaas.com and that PRs to that repo need to be made to keep get.sh in sync.

We could even add a note to the contributing guide in the top of the get.sh file stating its source and where it is served from.

I also noted get.sh didn't have `#!/bin/bash` at the top of the file?

### PR DESCRIPTION
**Pull request by burtonr**
## Description

Added link to repo for updates to the get.sh file
Removed the `get.sh` script as it is now located on cli.openfaas.com repo

Signed-off-by: Burton Rheutan <rheutan7@gmail.com>

## Motivation and Context

- [X] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

Resolves #586 

## How Has This Been Tested?

Documentation/comment only changes

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [X] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by burtonr** [comment]
@rgee0 Please let me know if you'd like any change to this. I saw it was sitting for a bit, and had some extra time. I could push any changes you request quickly.

Thanks!

**Comment by rgee0** [comment]
The original issue refers to keeping "get.sh in sync" - what does that mean?

**Comment by alexellis** [comment]
I can't remember but we don't need two copies of the file so let's delete the one from the original repo?

**Comment by burtonr** [comment]
Good point! Having the 2 scripts would likely cause confusion and issues later...

Removed `get.sh` from this repo

**Comment by alexellis** [comment]
Thanks both

**Pull request merged**
