### PR TITLE
Rename sirupsen

### PR DESCRIPTION
**Pull request by LucasRoesler**
## Description
- update the vendored Sirupsen -> sirupsen rename so that
  it is respected on case-senstive file systems

I used 

```sh
$ git config core.ignorecase false
```
to convince my git to recognize the renamed folder.

## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

Fixes release issue found in #823

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by alexellis — APPROVED** [review]
Approved

**Comment by alexellis** [comment]
Here is the release, and you can link through to the logs from there to see if it worked:

https://github.com/openfaas/faas-cli/releases/tag/0.12.11

**Comment by alexellis** [comment]
I'm seeing an errored status @LucasRoesler 

https://travis-ci.com/github/openfaas/faas-cli/builds/184169156?utm_medium=notification&utm_source=email

**Comment by LucasRoesler** [comment]
> https://travis-ci.com/github/openfaas/faas-cli/builds/184169156?utm_medium=notification&utm_source=email

```
# golang.org/x/sys/unix
vendor/golang.org/x/sys/unix/zptrace_armnn_linux.go:45:57: cannot use uint64(unsafe.Sizeof(*regsout)) (type uint64) as type uint32 in field value
vendor/golang.org/x/sys/unix/zptrace_armnn_linux.go:51:54: cannot use uint64(unsafe.Sizeof(*regs)) (type uint64) as type uint32 in field value
```

not sure what is happening and why this _only_ happens during the tag builds. In both PRs i have run the redist command successfully locally

**Pull request merged**
