### PR TITLE
Add root user to Dockerfile for Google Cloud Build

### PR DESCRIPTION
**Pull request by utsavanand2**
## Description

Adds a root user to DockerImage for the CI flow so the faas-cli root docker image can be used with CI/CD platforms like Google Cloud Build, check out #804 for detailed findings of what this PR will bring.

## Motivation and Context

Issue #809 
- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## How Has This Been Tested?

Check it out here in the [comment](https://github.com/openfaas/faas-cli/pull/813#issuecomment-644630868)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by utsavanand2** [comment]
Here are the logs of the travis build 
https://travis-ci.org/github/utsavanand2/faas-cli/builds/698840727

Here are the Docker Images pushed during CI
https://hub.docker.com/repository/docker/utsavanand2/faas-cli

And to prove that the non-root user using `CMD` to invoke faas-cli and the root user using `ENTRYPOINT` to invoke faas-cli `docker inspect ...` shows the output as under:

0.12.5:
Screenshot 2020-06-16 at 2 22 32 PM

0.12.5-root:
Screenshot 2020-06-16 at 2 23 29 PM

**Comment by utsavanand2** [comment]
If you guys give it a go, I'll go ahead and revert the deploy keys back to the ones that belong to OpenFaas's github repo

**Comment by LucasRoesler** [comment]
@utsavanand2 i tried the images and they work as expected, but i think i would prefer that both use entrypoint or both use cmd so that you can easily switch from one to the other by just swapping the tag

**Comment by utsavanand2** [comment]
@LucasRoesler Yes that would be awesome! I guess using `CMD` won't work for Google Cloud Build when using commands where multiple commands need to be piped for e.g., using `echo $PASSWORD | faas-cli login --password-stdin`. These places give trouble when using `CMD` whereas the same command works fine for the `echo $PASSWORD | docker login --password-stdin --user $USER`. So in my opinion moving to `ENTRYPOINT` makes more sense.

**Comment by alexellis** [comment]
Please can you change the non-root image to also use `ENTRYPOINT`? cc @LucasRoesler

**Comment by utsavanand2** [comment]
@alexellis Looks like we're good to go now?

**Pull request merged**
