### PR TITLE
Remove template from faas-cli repo

### PR DESCRIPTION
**Pull request by stantonxu**
Fixes https://github.com/openfaas/faas/issues/658. As we have a `template` repo separately, remove the "template" folder from the `faas-cli` repo.

Signed-off-by: Jiefeng "Stanton" Xu <xjiefeng@gmail.com>

## Description

Remove the "template" folder in the `faas-cli` repo. The default template will be pulled from the `template` repo.

The `template` repo https://github.com/openfaas/templates was added to the CLI as the default source to pull template. The change was made [here](https://github.com/openfaas/faas-cli/commit/2a1a81d58efc41c5f2b292bec4ee8913ddcf5bb9) on Dec 6 2017, and was release in [0.5.2](https://github.com/openfaas/faas-cli/releases/tag/0.5.2) on Jan 17 2018. Anyone using an earlier version will be affected by that change.

## Motivation and Context

Fixes https://github.com/openfaas/faas/issues/658

- [] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))
This is for an open issue https://github.com/openfaas/faas/issues/658

## How Has This Been Tested?

Ran `go test` for `faas-cli` repo and passed.

Env:
macOS Sierra Version 10.12.4
Go 1.9.6

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by rgee0** [comment]
Reiterating the comment on https://github.com/openfaas/faas/issues/658#issuecomment-397793093

This is potentially a breaking change for some users and so timing of any merge will be a consideration. In light of that please provide details of affected versions and dates in the PR detail as this will help the decision process.

**Comment by stantonxu** [comment]
@rgee0 @alexellis , thanks for your comments. Is there a template for the affected versions and dates to be included in the PR details?

By the way, it depends on when you guys decide to approve and merge the PR. I see the current released version is 0.6.10 by Alex on Jun 5th. So should I say that the affected versions are 0.6.10 and below, and dates are Jun 5th and before?

**Comment by rgee0** [comment]
The description field is adequate to store details of affected versions.  We're looking for something along the lines of _the template repo address was added to the CLI in v0.2 which was released on dd/mm/yyyy. Anyone using a **earlier** version will be affected by this change._ 

Alex has covered when the templates moved, which will likely be around a similar time.  Lets make sure we know from the CLI angle too.

**Comment by alexellis** [comment]
( We have some duplicate discussion on the PR and original issue - so please look at both when viewing this PR. )

**Comment by stantonxu** [comment]
@rgee0 , description updated, please review and let me know your comments.

**Comment by rgee0** [comment]
The change to retrieve templates from openfaas/templates was made [here](https://github.com/openfaas/faas-cli/commit/2a1a81d58efc41c5f2b292bec4ee8913ddcf5bb9) on 6 Dec 2017.

This was released in [0.5.2](https://github.com/openfaas/faas-cli/releases/tag/0.5.2) on 17 Jan 2018.

Anyone using versions prior to 0.5.2 will see an error when trying to pull templates once this change is merged.

**Comment by stantonxu** [comment]
I was mistakenly looking into "xxx commits to master since this release", and it was of course listed there for v0.2... Sorry for the overlook. Description updated for both PR and the issue.

**Comment by stantonxu** [comment]
@alexellis @rgee0 @BurtonR Any other suggestions? Or is it ready to merge?

**Comment by BurtonR** [comment]
I think it looks good. Once this gets merged, please also add a comment to the issue as you did in the description here indicating the dates and versions that the other template change was made. Just to be sure if someone does a search, they'll be able to find the information as easy as possible.

Thanks @stantonxu!

**Comment by stantonxu** [comment]
Thanks @BurtonR , I've already added that comment in the issue.

**Comment by alexellis** [comment]
Do we have consensus to merge this now @rgee0?

**Comment by rgee0** [comment]
I'm trying to minimize the potential impact in support terms by making sure we have the right information readily available within issues and PRs.  I think once we get the issue updated as per @BurtonR's comment and the description here doesn't have a dangling _"which was released on Jun 01 2017"_ we should be good to go.

**Comment by stantonxu** [comment]
@rgee0 , good catch, thanks. I've updated both the PR and the issue. We should be good to go.

**Comment by alexellis** [comment]
Ok glad we're all on the same page. Let's do it. Thanks to all for collaborating.

**Pull request merged**
