### PR TITLE
Add `ls` alias for `faas-cli list` command

### PR DESCRIPTION
**Pull request by ericstoekl**
Signed-off-by: Eric Stoekl <ems5311@gmail.com>

This change adds the `ls` alias for the `faas-cli list` command.

I feel that these changes make hacking on OpenFaaS just a bit faster, and require very little code change, so it might be worth it to include them in the build.

## Description

Adds the `ls` alias to `faas-cli list` command.

## Motivation and Context
Typing the full `faas-cli list` command can be tedious, so this may help reduce the time it takes to iterate.

- [X] I have raised an issue to propose this change ([required](https://github.com/alexellis/faas/blob/master/CONTRIBUTING.md))
#122 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I've read the [CONTRIBUTION](https://github.com/alexellis/faas/blob/master/CONTRIBUTING.md) guide
- [X] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by johnmccabe** [comment]
The `ls` is reasonable, but I don't like the `b` or `d`, if someone wants to use shortcuts that drastic they can always create their own aliases in their shell.

**Comment by ericstoekl** [comment]
Thanks for your feedback John. Updated the PR to only include the 'ls' alias.

**Comment by johnmccabe** [comment]
Can you update the description as well please.

**Comment by johnmccabe** [comment]
Also is there an issue raised for this?

**Comment by ericstoekl** [comment]
Updated description, and linked issue #122

**Comment by alexellis** [comment]
Agree with points made by @johnmccabe. Thanks for adding the alias.

**Pull request merged**
