### PR TITLE
Add perl as supported language

### PR DESCRIPTION
**Pull request by pari-**
Signed-off-by: Patrick Ringl <patrick_@freenet.de>

## Description
OpenFAAS goes TIMTOWTDI

## Motivation and Context
I love perl! ;-)

## How Has This Been Tested?
Stating the obvious: by *using* it .. and honestly: enjoying it thus far :-)

## Types of changes
- [x] New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/alexellis/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.

PS: I deliberately rearranged the supported language enumeration where I saw fit, since ordering make enumerations much more intuitive to read - hope you don't mind, though.

regards,
pari

### CODE REVIEW

**Comment by alexellis** [comment]
Hi, this looks interesting - Perl is certainly useful for scripts.

Did you read the contribution guide which asks folks to raise a proposal
issue to discuss before raising a PR?

**Comment by pari-** [comment]
Yup, I did. But: while playing with OpenFAAS, evaluating it as a potential first-class citizen of my actual to-be-implemented use-case, I discovered how intuitive it'd be to integrate my favourite programming language - and that's how I arrived at submitting this PR! :-)

**Comment by alexellis** [comment]
I'm really glad to hear that - the changes look good. We're starting to pin down the core languages which will be supported by myself and any core contributors and those which will be community-supported. Related: #86 #85

**Comment by alexellis** [comment]
Derek add label: revisit

**Comment by pari-** [comment]
@alexellis will do, once #87 is merged.

**Comment by ericstoekl** [comment]
@pari-  I just tried this out but it's not giving me any output when I pass data to STDIN. This happens when calling the function directly within the container:

```
# echo -n stuff | carton exec perl index.pl
# 
```

Where I would expect `"Hello world from the Perl template"`

Is this expected?

**Comment by alexellis** [comment]
@pari- we'd like your template, but you will need to create it in its own GitHub repo. Please comment on #54 when you have that ready. I'm going to close this PR now.

**Comment by alexellis** [comment]
@pari- please create your template.. we can support it now. Checkout the README for instructions.

**Pull request closed without merging**
