### PR TITLE
Add ReadOnlyRootFilesystem to the schema

### PR DESCRIPTION
**Pull request by LucasRoesler**
## Description

- Add the ReadOnlyRootFilesystem option to the stack schema
- Pass the value of ReadOnlyRootFilesystem to the create function
request
- Update the vendor lock to bunp the faas version
- Update the vendor lock to include docker-credential-helper because it
was required to build correctly

## Motivation and Context

- [X] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md)

Closes openfaas/faas#590

This will be parsed into the add function request and then to the
orchestration layer so that the function container is created with a
read-only filesystem at /)

## How Has This Been Tested?

I am posting this to get it in the pipeline and ready for testing, I will start testing it as soon as I have the companion pull requests in swarm and netes ready.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [X] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
@LucasRoesler I'd say we need to add a `prune` setting to the vendoring config here.. see faas-netes as an example. I think it's in some of the other repos too. Setting goes in Gopkg.toml and prevents all the extra unrelated files/packages being copied in. 

Alex

**Comment by alexellis** [comment]
Restarting build after #441 fixed by @burtonr  - https://travis-ci.org/openfaas/faas-cli/builds/404566411

Please also see note on prune for vendoring tool.

**Comment by alexellis** [comment]
```
[prune]
  go-tests = true
  unused-packages = true
```

**Comment by LucasRoesler** [comment]
I just added pruning and pushed the update, it unfortunately is still a large PR because of pruning all of vendor

**Comment by alexellis** [comment]
I'm ok with that. I'd just want to see that the credential manager still works and the tests/build. 

Alex

**Comment by LucasRoesler** [comment]
I am going to try and rewrite the PR into two commits, one with the code changes and one with the vendor prune

**Comment by alexellis** [comment]
This should be squashed onto one commit so that we don't add all those dependencies and then remove them in the next commit - the history will bloat I would think. 

Approach looks good to me for the flag.

Alex

**Comment by LucasRoesler** [comment]
If anyone else wants to look at it, the first commit is the actual change, if we are really good with it I can squash it before we merge

**Comment by Templum** [comment]
@LucasRoesler currently it seems you only pass on the variable. But don't provide a way to set it. That can be done in `commands/deploy.go` & `stack/schema.go`.

1.  Extend `type DeployFlags struct`to include the new flag
2. Add it to the deployCmd `deployCmd.Flags().BoolVarP(&deployFlags. ReadOnlyRootFilesystem, "read-only-fs", "r", false, "Enables an read only file system for the function")`
3. Alter `readOnlyRootFilesystem := false` => `readOnlyRootFilesystem := deployFlags.ReadOnlyRootFilesystem`. (If not set it should default to false, like specified in 2.)
4. Add ReadOnlyRootFilesystem bool \`json:"readOnlyRootFilesystem"\` to `schema.go`

You can have a look at what I did [here](https://github.com/openfaas/faas-cli/pull/439/commits/eb670ce8a40e87e58922faba2c984c39267aa0c4).

**Comment by LucasRoesler** [comment]
Should I revert 1c6ef82

**Comment by alexellis** [comment]
Commented on the commit. Think we could leave it in.

**Comment by alexellis** [comment]
Commented on the commit. Think we could leave it in.

**Comment by alexellis** [comment]
Naming is too verbose for the flag IMHO

**Comment by alexellis** [comment]
Hi @LucasRoesler two PRs were merged recently so this will need a quick rebase.

Alex

**Comment by alexellis** [comment]
Derek set milestone: 0.6.16

**Comment by LucasRoesler** [comment]
I just rebased and squashed this PR now that the changes to the vendor settings are in master.  The PR is more concise and ready for a real review

**Comment by alexellis** [comment]
Thank you for doing that. Merged now 👍

**Pull request merged**
