### PR TITLE
Feature go modules migration

### PR DESCRIPTION
**Pull request by LucasRoesler**
## Description

"Upgrade" to Go modules by replacing the dep lock/toml with go mod/sum.  Then, update vendor folder.

## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## How Has This Been Tested?

I have run `make build` and `make build_redist` to test the docker builds.  I have also use `make local-install` and then tested the mac and linux binaries

I have also run the unit tests via `make test-unit`

In all cases the binaries build correctly or tests pass.

I have also done a quick test of 
- the build and deploy for a function, 
- the create and delete for a secret, 
- and logs
all of these are working in my tests.

Most of the changes have to deal with updating the docker `term` package, which allows us to deal with the logrus name change and the fact that docker is not using semver/modules.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by tullo** [comment]
@LucasRoesler 
Try running: `go mod vendor`

It will add `vendor/github.com/sirupsen/logrus`
an delete `vendor/github.com/Sirupsen`

**Comment by LucasRoesler** [comment]
Hi @tullo i am not seeing it replace sirupsen on my machine

**Comment by tullo** [comment]
Strange, maybe it's an OS or Go version thing. I am on `go version && uname -omspr`
```bash
go version go1.13.1 linux/amd64
Linux 4.15.0-74-generic x86_64 x86_64 GNU/Linux
```

**Comment by LucasRoesler** [comment]
Possibly, I'm on mac

**Comment by LucasRoesler** [comment]
I used multipass to get an ubuntu vm

```sh
$ go version && uname -omspr
go version go1.13.6 linux/amd64
Linux 4.15.0-72-generic x86_64 x86_64 GNU/Linux
```

Still not changes when I run `go mod vendor`

```sh
$ go mod vendor && git status
On branch feature-go-modules-migration
Your branch is up to date with 'origin/feature-go-modules-migration'.

nothing to commit, working tree clean
```

I don't see anything obvious in the Go changelog that would explain the difference https://golang.org/doc/devel/release.html

Perhaps the VM isn't enough to really reproduce it

**Comment by tullo** [comment]
The go.mod says i need [github.com/sirupsen/logrus v1.4.2](https://github.com/openfaas/faas-cli/pull/757/commits/256e0edd131abbcbfc8706882ea75da849fe68d6#diff-37aff102a57d3d7b797f152915a6dc16R21)

and modules.txt shows the [replacement of Sirupsen](https://github.com/openfaas/faas-cli/pull/757/commits/256e0edd131abbcbfc8706882ea75da849fe68d6#diff-31be3fbc3cb3d1a36172f2111034b4ceR4) to sirupsen as far as I can tell

**Comment by LucasRoesler** [comment]
Perhaps your local copy is stale, try pulling again, that sounds like an old version of the mod file.  The current mod file should  be

```
module github.com/openfaas/faas-cli

go 1.13

replace github.com/docker/docker => github.com/docker/engine v1.4.2-0.20190717161051-705d9623b7c1

require (
	github.com/Azure/go-ansiterm v0.0.0-20170929234023-d6e3b3328b78 // indirect
	github.com/alexellis/go-execute v0.0.0-20191207085904-961405ea7544
	github.com/alexellis/hmac v0.0.0-20180624210714-d5d71edd7bc7
	github.com/docker/docker v1.13.1
	github.com/docker/docker-credential-helpers v0.6.3
	github.com/drone/envsubst v1.0.2
	github.com/mitchellh/go-homedir v1.1.0
	github.com/morikuni/aec v1.0.0
	github.com/openfaas/faas v0.0.0-20191128202628-4d4ecc6bbf98
	github.com/openfaas/faas-provider v0.0.0-20191005090653-478f741b64cb
	github.com/pkg/errors v0.8.1
	github.com/ryanuber/go-glob v1.0.0
	github.com/sirupsen/logrus v1.4.2 // indirect
	github.com/spf13/cobra v0.0.5
	github.com/spf13/pflag v1.0.5
	go.uber.org/goleak v1.0.0 // indirect
	gopkg.in/yaml.v2 v2.2.7
	gotest.tools v2.2.0+incompatible // indirect
)
```

**Comment by tullo** [comment]
The links in my previous message point to the files in this PR

I see that `.travis.yml` currently sets env to `GO111MODULE=off`

I can reproduce it with these steps:
* `go clean -modcache
* `GO111MODULE=on go mod download`
* `GO111MODULE=on go mod vendor`

**Comment by LucasRoesler** [comment]
@tullo you are right your link is to a file in this PR, one commit old. The code you are using _is_ incorrect, but has been updated in d78b9f9

**Comment by tullo** [comment]
Hmm, ok. Here are the steps I just did on fresh ubuntu box. Maybe I'm doing it wrong?

```bash
git clone https://github.com/LucasRoesler/faas-cli.git

cd faas-cli/

git checkout feature-go-modules-migration

git log --oneline 
d78b9f9 (HEAD -> feature-go-modules-migration, origin/feature-go-modules-migration) Add better fix for docker term package

GO111MODULE=on go mod download

GO111MODULE=on go mod vendor

git status 
On branch feature-go-modules-migration
Your branch is up to date with 'origin/feature-go-modules-migration'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	deleted:    vendor/github.com/Sirupsen/logrus/.gitignore
	deleted:    vendor/github.com/Sirupsen/logrus/.travis.yml
	deleted:    vendor/github.com/Sirupsen/logrus/CHANGELOG.md
	deleted:    vendor/github.com/Sirupsen/logrus/LICENSE
	deleted:    vendor/github.com/Sirupsen/logrus/README.md
	deleted:    vendor/github.com/Sirupsen/logrus/alt_exit.go
	deleted:    vendor/github.com/Sirupsen/logrus/appveyor.yml
	deleted:    vendor/github.com/Sirupsen/logrus/doc.go
	deleted:    vendor/github.com/Sirupsen/logrus/entry.go
	deleted:    vendor/github.com/Sirupsen/logrus/exported.go
	deleted:    vendor/github.com/Sirupsen/logrus/formatter.go
	deleted:    vendor/github.com/Sirupsen/logrus/go.mod
	deleted:    vendor/github.com/Sirupsen/logrus/go.sum
	deleted:    vendor/github.com/Sirupsen/logrus/hooks.go
	deleted:    vendor/github.com/Sirupsen/logrus/json_formatter.go
	deleted:    vendor/github.com/Sirupsen/logrus/logger.go
	deleted:    vendor/github.com/Sirupsen/logrus/logrus.go
	deleted:    vendor/github.com/Sirupsen/logrus/terminal_check_appengine.go
	deleted:    vendor/github.com/Sirupsen/logrus/terminal_check_bsd.go
	deleted:    vendor/github.com/Sirupsen/logrus/terminal_check_no_terminal.go
	deleted:    vendor/github.com/Sirupsen/logrus/terminal_check_notappengine.go
	deleted:    vendor/github.com/Sirupsen/logrus/terminal_check_solaris.go
	deleted:    vendor/github.com/Sirupsen/logrus/terminal_check_unix.go
	deleted:    vendor/github.com/Sirupsen/logrus/terminal_check_windows.go
	deleted:    vendor/github.com/Sirupsen/logrus/text_formatter.go
	deleted:    vendor/github.com/Sirupsen/logrus/writer.go

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	vendor/github.com/sirupsen/

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by LucasRoesler** [comment]
I have no explanation for that then

**Comment by tullo** [comment]
Just a thought - module aware go code only needs the go.mod file.

Is there any reason to support older go versions for this CLI? If not then the vendor folder can go away.

https://github.com/golang/go/wiki/Modules#how-do-i-use-vendoring-with-modules-is-vendoring-going-away

**Comment by alexellis** [comment]
Please see the contribution guide. Thank you for your input.

**Comment by alexellis** [comment]
If we suspect a bug with go modules or a custom environment, how about doing the experiment in a Go container instead. Then we have a consistent environment.

**Comment by LucasRoesler** [comment]
I just tried it in a docker container 

```sh
docker run -it --rm -v `pwd`:/app golang:1.13

GO111MODULE=on go mod download
GO111MODULE=on go mod vendor
```

but it made no changes to the vendor folder.

**Comment by tullo** [comment]
Unfortunately I still get the same result:

> docker run -it --rm -v `pwd`:/app golang:1.13
> root@b05260c52a8a:/go# cd /app/
> root@b05260c52a8a:/app# GO111MODULE=on go mod download
> root@b05260c52a8a:/app# GO111MODULE=on go mod vendor
> root@b05260c52a8a:/app# git status
> On branch feature-go-modules-migration
> Your branch is up to date with 'remotes/origin/feature-go-modules-migration'.
> 
> Changes not staged for commit:
>   (use "git add/rm <file>..." to update what will be committed)
>   (use "git checkout -- <file>..." to discard changes in working directory)
> 
> 	deleted:    vendor/github.com/Sirupsen/logrus/.gitignore
> 	deleted:    vendor/github.com/Sirupsen/logrus/.travis.yml
> 	deleted:    vendor/github.com/Sirupsen/logrus/CHANGELOG.md
> 	deleted:    vendor/github.com/Sirupsen/logrus/LICENSE
> 	deleted:    vendor/github.com/Sirupsen/logrus/README.md
> 	deleted:    vendor/github.com/Sirupsen/logrus/alt_exit.go
> 	deleted:    vendor/github.com/Sirupsen/logrus/appveyor.yml
> 	deleted:    vendor/github.com/Sirupsen/logrus/doc.go
> 	deleted:    vendor/github.com/Sirupsen/logrus/entry.go
> 	deleted:    vendor/github.com/Sirupsen/logrus/exported.go
> 	deleted:    vendor/github.com/Sirupsen/logrus/formatter.go
> 	deleted:    vendor/github.com/Sirupsen/logrus/go.mod
> 	deleted:    vendor/github.com/Sirupsen/logrus/go.sum
> 	deleted:    vendor/github.com/Sirupsen/logrus/hooks.go
> 	deleted:    vendor/github.com/Sirupsen/logrus/json_formatter.go
> 	deleted:    vendor/github.com/Sirupsen/logrus/logger.go
> 	deleted:    vendor/github.com/Sirupsen/logrus/logrus.go
> 	deleted:    vendor/github.com/Sirupsen/logrus/terminal_check_appengine.go
> 	deleted:    vendor/github.com/Sirupsen/logrus/terminal_check_bsd.go
> 	deleted:    vendor/github.com/Sirupsen/logrus/terminal_check_no_terminal.go
> 	deleted:    vendor/github.com/Sirupsen/logrus/terminal_check_notappengine.go
> 	deleted:    vendor/github.com/Sirupsen/logrus/terminal_check_solaris.go
> 	deleted:    vendor/github.com/Sirupsen/logrus/terminal_check_unix.go
> 	deleted:    vendor/github.com/Sirupsen/logrus/terminal_check_windows.go
> 	deleted:    vendor/github.com/Sirupsen/logrus/text_formatter.go
> 	deleted:    vendor/github.com/Sirupsen/logrus/writer.go
> 
> Untracked files:
>   (use "git add <file>..." to include in what will be committed)
> 
> 	vendor/github.com/sirupsen/
> 
> no changes added to commit (use "git add" and/or "git commit -a")
>

**Comment by justinfx** [comment]
I started trying some dev changes to faas-cli and only had to do the following to get modules working (using go 1.14):

1. `go mod init github.com/openfaas/faas-cli`
1. `go mod edit -replace=github.com/Sirupsen/logrus@v1.4.2=github.com/sirupsen/logrus@v1.4.2`

**Comment by LucasRoesler** [comment]
@justinfx you have to be careful with the docker/docker dependency, it will pull in a very old version of the package.  I used

```
replace github.com/docker/docker => github.com/docker/engine v1.4.2-0.20190717161051-705d9623b7c1
```
to pull in the more recent version of docker which also indirectly fixes the logrus version as well.

Did you try this branch?

**Comment by justinfx** [comment]
I didn't try this branch, no. I just came across this issue while searching for something similar to what I wanted to submit. And I saw the concerns with the logrus dep and thought I would just share that I was able to dev my first feature with Go modules support. I didn't use the docker features. Only local tests.

**Pull request closed without merging**
