### PR TITLE
Add appveyor CI for tests on Windows

### PR DESCRIPTION
**Pull request by itscaro**
In case it's worth using Appveyor

### CODE REVIEW

**Comment by alexellis** [comment]
What is this giving us over and above building with Linux and cross compilation?

**Comment by itscaro** [comment]
@alexellis it's just for running windows-specific test cases

**Comment by stefanprodan** [comment]
This would cover #186

**Comment by itscaro** [comment]
@stefanprodan thanks for pointing out the related issue

**Comment by alexellis** [comment]
What is available on the "free tier"? How long will it take us to cut releases and validate PRs if we have to do builds on AppVeyor and Travis?

**Comment by johnmccabe** [comment]
I would be inclined to just try this - can always revert/disable.

**Pull request closed without merging**
