### PR TITLE
Provide better error message when templates are missing in faas-cli deploy of non-Dockerfile language

### PR DESCRIPTION
**Pull request by ericstoekl**
## Description

An question was asked in the Slack channel about the confusing error message that you get when you try to deploy a function that uses a non-Dockerfile language and you don't have the `template/` folder in your present working directory. This change seeks to provide a better error message.

Before this change:

```
$ faas-cli deploy
Deploying: telegram-gif-bot.
Stat ./template/node/template.yml: no such file or directory
```

After this change:

```
$ faas-cli deploy
Deploying: telegram-gif-bot.
Deployment error: Couldn't get fprocess for function telegram-gif-bot. Make sure the language template for node is present in the ./template/ directory.
Stat ./template/node/template.yml: no such file or directory
```

## Motivation and Context

- [X] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))
https://github.com/openfaas/faas-cli/issues/307

## How Has This Been Tested?

A test is added to `commands/deploy_test.go` to exercise this code path.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [X] I have signed-off my commits with `git commit -s`
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by ericstoekl** [comment]
Side note -- This change adds test coverage for the YAML file path of the `RunDeploy()` function in `commands/deploy.go`, increasing the test coverage of `commands/` by 6% (from ~44% to ~50.6%)

**Comment by alexellis** [comment]
@ericstoekl perhaps we should have a new line in there for this message?

```
Deployment error: Couldn't get fprocess for function telegram-gif-bot. Make sure the language template for node is present in the ./template/ directory.
```

Could we come up with a less technical and more user-friendly message too?

**Comment by alexellis** [comment]
Ping @ericstoekl

**Comment by ericstoekl** [comment]
I updated this item a few days ago but forgot to comment on it. I've adjusted the error message to be more user friendly (IMO)

**Comment by viveksyngh** [comment]
@ericstoekl  I was testing this PR. Right now it gives below error when `template` folder is not present

````
 >> /Users/viveks/Repos/go-projects/src/github.com/openfaas/faas-cli/faas-cli deploy
Deploying: duration-test.
Language not found: pythonStat ./template/python/template.yml: no such file or directory
```

We should put a space between `python` and `Stat` to make it more readable.

**Comment by ericstoekl** [comment]
Good catch @viveksyngh , thanks for the review. I've updated to fix that and sync to latest version of the `master` branch.

**Comment by alexellis** [comment]
I'm closing this so we can get something smaller in quicker. Thanks for working on it Eric.

**Pull request closed without merging**
