### PR TITLE
Update Go version to 1.11

### PR DESCRIPTION
**Pull request by alexellis**
Updates Go version to 1.11 

Signed-off-by: Alex Ellis (VMware) <alexellis2@gmail.com>

## Description

This is the current version of Golang, but could do with more exploratory testing from the community before merging. @stefanprodan may also have other input having commented about this version and static binaries in the past.

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

https://github.com/openfaas/faas/issues/875

## How Has This Been Tested?

Unit tests pass and ran some exploratory tested with
build_redist.sh and binaries used on MacOS, Arch Linux (x86_64)
and Raspbian (armhf).

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by alexellis** [comment]
They need to be moved to 3.8 per https://github.com/openfaas/faas/issues/875

**Comment by stefanprodan** [comment]
I would change the go version in travis file also so that we'll use the same version everywhere.

**Comment by alexellis** [comment]
I am wondering if we need the Go runtime at all for this build? 

https://github.com/openfaas/faas-cli/blob/master/.travis.yml

We seem to do everything in Docker.. @ewilde what do you think?

**Comment by ewilde** [comment]
Yeah good point, worth testing on your feature branch without travis go support

**Comment by alexellis** [comment]
It worked 👍

**Pull request merged**
