### PR TITLE
Enable extended resource definitions for scheduling purposes.

### PR DESCRIPTION
**Pull request by feri**
## Description

* FunctionResources was extended with a new field called Others. This field stores extended resource definitions. Others is a map of strings, where the keys and values are pure strings.
* A new unmarshaler was added for the FunctionResources struct. When the function manifest YAML is parsed this unmarshaler will validate and sanitize resource definitions. CPU and Memory requests are passed as they are, while other definitions are tested against a regexp.
* The valid format of an extended resource for now is "vendor.domain/[gpu,fpga]", where vendor and domain can be any string. It's important to have a . [dot] between the two. After / [slash] the only valid resource names are gpu or fpga. This part should be documented in the appropriate place.
* Tests have also been added for the new unmarshaler.

## Motivation and Context
The motivation behind the patch is to enable deployment of functions that require extended resources such as GPUs or FPGAs. This will hopefully contribute for the fix of [issue 639 in faas](https://github.com/openfaas/faas/issues/639).
- [ ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## How Has This Been Tested?
The changes were tested in a Kubernetes (v1.11.0) cluster including 4 nodes. One of the nodes is running the [Intel Device Plugin](https://github.com/otcshare/kubernetes-intel-device-plugins) and exposes the integrated Intel GPU of that computer.
During the tests I was checking if scheduling is handled properly, ie. loads (functions) requesting "intel.com/gpu" are properly directed to the node mentioned before, or they were skipped if the node "ran out" of the specified resource, or was taken away from the cluster.
Docker swarm tests could not be carried out yet.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by feri** [comment]
@alexellis this PR is hopefully passing all the check. What is the standard procedure from here onwards? Shall I request a review from the team or something else? Could you please let me know how to proceed?

**Comment by alexellis** [comment]
Hi @feri, we have ongoing work for the release around read-only filesystems and annotations, so can't review and merge this until is done, but it's on my radar and I'll add it to the Trello roadmap (you can access this in #contributors in Slack)

Alex

**Comment by feri** [comment]
Understood, thanks @alexellis for the quick answer. I'll check Trello meanwhile. Cheers!

**Comment by feri** [comment]
@stefanprodan I also patched faas-netes to enable these things on the server / k8s side. There is a [PR too](https://github.com/openfaas/faas-netes/pull/264).

**Comment by feri** [comment]
The patch needs a re-write as the syntax for defining limits for extended resources [have changed](https://github.com/intel/intel-device-plugins-for-kubernetes/blob/master/demo/intelgpu-job.yaml#L22). It means that the [PR for faas-netes](https://github.com/openfaas/faas-netes/pull/264) is also outdated.

**Pull request closed without merging**
