### PR TITLE
Non root templates for node-armhf and python-armhf

### PR DESCRIPTION
**Pull request by austinfrey**
## Description

Update `python-armhf` and `node-armhf` Dockerfiles to use the `app` user.

## Motivation and Context

Adds security by adding  non-root user

Issue #81 
- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))
Issue #81 

## How Has This Been Tested?

Node and Python functions were built using the new Dockerfiles. Both functions worked as expected. I also `exec`'d into the container and made sure is was running as the `app` user

Docker Swarm on raspberry pi 3

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by johnmccabe** [comment]
@ericstoekl do you still have your Pi-based Swarm up and running, if so could you review this for @austinfrey ?

**Comment by alexellis** [comment]
Thanks for the PR Austin. I agree with @johnmccabe - need it to be tested independently.

**Comment by ericstoekl** [comment]
I have just manually tested this PR and I sign off on it. Created a function using the `node-armh` template and a function using the `python-armhf` template. Both work and show that `app` is the user, as well as the `/tmp/.lock` file is present.

**Comment by alexellis** [comment]
We'll need this on the faas/templates repo marking as #revisit.

**Comment by alexellis** [comment]
Derek add label: revisit

**Pull request closed without merging**
