### PR TITLE
Exit+throw error on version not found in get.sh

### PR DESCRIPTION
**Pull request by ericstoekl**
Signed-off-by: Eric Stoekl <ems5311@gmail.com>

## Description

The quick-install script should throw an error if it doesn't successfully get the latest version of `faas-cli` available. This can be caused by Github API's [rate limiter](https://developer.github.com/v3/#rate-limiting).

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))
https://github.com/openfaas/faas-cli/issues/377

## How Has This Been Tested?

Checked that the `if` statement works correctly when the `$version` variable is null.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
@rgee0 please could you take a look at Eric's PR?

**Comment by rgee0** [comment]
@ericstoekl looks fine to me.  The only point to raise is should we offer the same commands as the non-root message and advise the user to also run `ln -sf /usr/local/bin/faas-cli /usr/local/bin/faas`?

**Comment by ericstoekl** [comment]
Updated to take suggestion from @rgee0

**Comment by rgee0** [comment]
LGTM

**Pull request merged**
