### PR TITLE
Add F# template via @hayer

### PR DESCRIPTION
**Pull request by alexellis**
Add F# template via @hayer

Signed-off-by: Alex Ellis <alexellis2@gmail.com>

## Description

Proposed template by @hayer for FSharp.

Blocking changes:
- [ ] Wait for @hayer to add README.md to repository
- [ ] Wait for @hayer to add LICENSE of MIT to repository

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

#343 

## How Has This Been Tested?

Requires testing

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
@hayer please see the `Blocking changes:` in this PR and once you've resolved these and I've tested the template I'll merge the PR.

**Comment by hayer** [comment]
I think that should do it? 😄 Thanks for creating the PR

**Comment by alexellis** [comment]
@BurtonR as our resident .NET expert please could you try the template and provide feedback if necessary? If you think it's good to go I'll merge this PR into the community list.

**Comment by BurtonR** [comment]
Sure thing! I'll check it out this evening and post back my results here

**Comment by BurtonR** [comment]
Tested by running the following commands:
```bash
faas template pull https://github.com/hayer/faas-fsharp-template/
faas new --lang fsharp testing
faas build -f ./testing.yml
faas deploy -f ./testing.yml
echo "try functional faas!" | faas invoke testing
```

Added some functionality to the template and repeated the above tests.

Everything looks good! Nice work @hayer! :+1:

**Comment by alexellis** [comment]
Thank you @BurtonR - @hayer I've merged your template into the community list.

**Pull request merged**
