### PR TITLE
building faas-cli for ppc64le

### PR DESCRIPTION
**Pull request by aklyachkin**
Signed-off-by: Andrey Klyachkin <aklyachkin@gmail.com>

## Description
build faas-cli for ppc64le added.

## Motivation and Context
- [X] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

https://github.com/aklyachkin/faas-cli.git

## How Has This Been Tested?
Compiled, run on ppc64le platform

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [X] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Quick question - why is this needed? It's a client, so I would expect it not to be needed on the powerPC which is a server-only?

**Comment by aklyachkin** [comment]
the same problem as with arm - if you build a docker image on x86_64 it is amd64 image and can't be run on ppc64le. You have to rebuild images on ppc64le and it is easier if you have faas-cli and can just use the same procedure - faas-cli build, faas-cli deploy...

**Comment by alexellis** [comment]
@aklyachkin do you still need this?

**Comment by alexellis** [comment]
Having a clear-up on GitHub issues / PRs over 1 month old. Let's revisit as necessary. Thank you for the PR.

**Pull request closed without merging**
