### PR TITLE
Improve output for rolling updates

### PR DESCRIPTION
**Pull request by ericstoekl**
Signed-off-by: Eric Stoekl <ems5311@gmail.com>

## Description

The purpose of this PR is to make the output for `faas-cli deploy` more clear when a rolling update is triggered, or when a rolling update fails and a regular 'create' deploy is triggered.

The output now looks like:

Function already exists:
```
$ faas-cli deploy --name echo --image functions/faas-echo:latest --gateway $gw

Function echo already exists, attempting rolling-update.
Deployed (updated)
URL: http://192.168.99.100:8080/function/echo

200 OK
```

Function does not yet exist:

```
$ faas-cli deploy --name echo --image functions/faas-echo:latest --gateway $gw

Function not found, attempting deployment.
Deployed
URL: http://192.168.99.100:8080/function/echo

200 OK
```

## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))
This change was proposed by Alex here: https://github.com/openfaas/faas-cli/pull/257#issuecomment-354670227

## How Has This Been Tested?

Existing tests pass, only change here is to output messages, no implementation changes.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [X] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by BurtonR** [comment]
So much cleaner! Nice work @ericstoekl! 💯 

```
burtonr@codefox : ~/code/faas
[0] % ./faas-cli deploy -f movies.yml                               
Updating: movies.

Function movies already exists, attempting rolling-update.
Deployed (updated)
URL: http://localhost:8080/function/movies

200 OK


burtonr@codefox : ~/code/faas
[0] % ./faas-cli deploy -f movies.yml
Updating: movies.

Function not found, attempting deployment.
Deployed
URL: http://localhost:8080/function/movies

200 OK
```

**Comment by alexellis** [comment]
Much better.. can you tweak it to this?

```
burtonr@codefox : ~/code/faas
[0] % ./faas-cli deploy -f movies.yml                               
Deploying: movies.
Function movies already exists, attempting rolling-update.

Deployed. 200 OK.
URL: http://localhost:8080/function/movies
```

```
burtonr@codefox : ~/code/faas
[0] % ./faas-cli deploy -f movies.yml
Deploying function: movies.

Deployed: 200 OK
URL: http://localhost:8080/function/movies
```

**Comment by ericstoekl** [comment]
Just updated this to have the output match what was requested by Alex:

```
~/github/go/src/github.com/openfaas/faas-cli $ fc deploy -f samples.yml 
Deploying: url-ping.
Function url-ping already exists, attempting rolling-update.

Deployed. 200 OK.
URL: http://localhost:8080/function/url-ping

~/github/go/src/github.com/openfaas/faas-cli $ fc rm -f samples.yml
Deleting: url-ping.
Removing old function.
~/github/go/src/github.com/openfaas/faas-cli $ fc deploy -f samples.yml 
Deploying: url-ping.

Deployed. 200 OK.
URL: http://localhost:8080/function/url-ping

```

**Comment by alexellis** [comment]
Great stuff 👍 thank you.

**Pull request merged**
