### PR TITLE
Add sort order to generate command

### LINKED ISSUE #777: Feature request: sorted output from "faas-cli generate" command
The output of `faas-cli generate --envsubst=false` is not deterministic.
It appears to choose a document order at random. This makes git diffs essentially useless on the output.

## Expected Behaviour
When I run the command with the same inputs, the output should be unchanged.

## Current Behaviour

The output is not sorted.

## Steps to Reproduce (for bugs)

1. Run on any YAML, for example [this folder](https://github.com/openfaas/openfaas-cloud/tree/master/yaml)
2. Run it again, and observe a different output.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ): 0.12.0

* Operating System and version (e.g. Linux, Windows, MacOS): Linux

### PR DESCRIPTION
**Pull request by rgee0**
Signed-off-by: Richard Gee <richard@technologee.co.uk>

## Description
This change seeks to introduce a pre-processing stage where a slice of function names is created and a rudimentary sort applied. This slice is then used to iterate through the map using the function name.

## Motivation and Context
The output from faas-cli generate is not deterministic.  The function detail is stored in a map which is by design non-deterministic.
This behaviour is undesirable as generating from the same stack will result in a different output, hence makes tracking diffs, particularly in git, quite a challenge.

- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))
Fixes #777

## How Has This Been Tested?
Previous mode of operation is described in https://github.com/openfaas/faas-cli/issues/777#issuecomment-797420368.  The following is provided as a comparison.
### Testing output
```
$ faas-cli version
  ___                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|

CLI:
 commit:  2ef6d23a62d371d72a6fcdc7cb87afeccde4a001-dirty
 version: 0.6.13-365-g2ef6d23a
Your faas-cli version (0.6.13-365-g2ef6d23a) may be out of date. Version: 0.13.9 is now available on GitHub.
```
* Check stack.yml being used:
```
$ cat fn1.yml
version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  fn1:
    lang: python3
    handler: ./fn1
    image: fn1:latest

  fn2:
    lang: python3
    handler: ./fn2
    image: fn2:latest

  fn3:
    lang: python3
    handler: ./fn3
    image: fn3:latest

  fn4:
    lang: python3
    handler: ./fn4
    image: fn4:latest

  fn5:
    lang: python3
    handler: ./fn5
    image: fn5:latest

  fn6:
    lang: python3
    handler: ./fn6
    image: fn6:latest

  fn7:
    lang: python3
    handler: ./fn7
    image: fn7:latest

  fn8:
    lang: python3
    handler: ./fn8
    image: fn8:latest

  fn9:
    lang: python3
    handler: ./fn9
    image: fn9:latest

  fn10:
    lang: python3
    handler: ./fn10
    image: fn10:latest

  fn11:
    lang: python3
    handler: ./fn11
    image: fn11:latest

  fn12:
    lang: python3
    handler: ./fn12
    image: fn12:latest

  fn13:
    lang: python3
    handler: ./fn13
    image: fn13:latest

  fn14:
    lang: python3
    handler: ./fn14
    image: fn14:latest

  fn15:
    lang: python3
    handler: ./fn15
    image: fn15:latest

  fn16:
    lang: python3
    handler: ./fn16
    image: fn16:latest

  fn17:
    lang: python3
    handler: ./fn17
    image: fn17:latest

  fn18:
    lang: python3
    handler: ./fn18
    image: fn18:latest

  fn19:
    lang: python3
    handler: ./fn19
    image: fn19:latest

  fn20:
    lang: python3
    handler: ./fn20
    image: fn20:latest
```
* Run generate 20 times against the stack.yml to create a set of generated files from the same input.
```
$ for i in {1..20}; do faas-cli generate  -f fn1.yml > ./generated2/$i.yml ; done
$ ls generated2
1.yml	10.yml	11.yml	12.yml	13.yml	14.yml	15.yml	16.yml	17.yml	18.yml	19.yml	2.yml	20.yml	3.yml	4.yml	5.yml	6.yml	7.yml	8.yml	9.yml
```
* Compare all generated files to find any differences:
```
$ cd generated2 
$ for i in {1..20}; do for j in {1..20}; do cmp -b $i.yml $j.yml >> diffs.txt ; done ; done
$ cat diffs.txt 
$ 
```
No differences observed
* Compare two generated files in detail to confirm
```
---								---
apiVersion: openfaas.com/v1					apiVersion: openfaas.com/v1
kind: Function							kind: Function
metadata:							metadata:
  name: fn1							  name: fn1
spec:								spec:
  name: fn1							  name: fn1
  image: fn1:latest						  image: fn1:latest
---								---
apiVersion: openfaas.com/v1					apiVersion: openfaas.com/v1
kind: Function							kind: Function
metadata:							metadata:
  name: fn10							  name: fn10
spec:								spec:
  name: fn10							  name: fn10
  image: fn10:latest						  image: fn10:latest
---								---
apiVersion: openfaas.com/v1					apiVersion: openfaas.com/v1
kind: Function							kind: Function
metadata:							metadata:
  name: fn11							  name: fn11
spec:								spec:
  name: fn11							  name: fn11
  image: fn11:latest						  image: fn11:latest
---								---
apiVersion: openfaas.com/v1					apiVersion: openfaas.com/v1
kind: Function							kind: Function
metadata:							metadata:
  name: fn12							  name: fn12
spec:								spec:
  name: fn12							  name: fn12
  image: fn12:latest						  image: fn12:latest
---								---
apiVersion: openfaas.com/v1					apiVersion: openfaas.com/v1
kind: Function							kind: Function
metadata:							metadata:
  name: fn13							  name: fn13
spec:								spec:
  name: fn13							  name: fn13
  image: fn13:latest						  image: fn13:latest
---								---
apiVersion: openfaas.com/v1					apiVersion: openfaas.com/v1
kind: Function							kind: Function
metadata:							metadata:
  name: fn14							  name: fn14
spec:								spec:
  name: fn14							  name: fn14
  image: fn14:latest						  image: fn14:latest
---								---
apiVersion: openfaas.com/v1					apiVersion: openfaas.com/v1
kind: Function							kind: Function
metadata:							metadata:
  name: fn15							  name: fn15
spec:								spec:
  name: fn15							  name: fn15
  image: fn15:latest						  image: fn15:latest
---								---
apiVersion: openfaas.com/v1					apiVersion: openfaas.com/v1
kind: Function							kind: Function
metadata:							metadata:
  name: fn16							  name: fn16
spec:								spec:
  name: fn16							  name: fn16
  image: fn16:latest						  image: fn16:latest
---								---
apiVersion: openfaas.com/v1					apiVersion: openfaas.com/v1
kind: Function							kind: Function
metadata:							metadata:
  name: fn17							  name: fn17
spec:								spec:
  name: fn17							  name: fn17
  image: fn17:latest						  image: fn17:latest
---								---
apiVersion: openfaas.com/v1					apiVersion: openfaas.com/v1
kind: Function							kind: Function
metadata:							metadata:
  name: fn18							  name: fn18
spec:								spec:
  name: fn18							  name: fn18
  image: fn18:latest						  image: fn18:latest
---								---
apiVersion: openfaas.com/v1					apiVersion: openfaas.com/v1
kind: Function							kind: Function
metadata:							metadata:
  name: fn19							  name: fn19
spec:								spec:
  name: fn19							  name: fn19
  image: fn19:latest						  image: fn19:latest
---								---
apiVersion: openfaas.com/v1					apiVersion: openfaas.com/v1
kind: Function							kind: Function
metadata:							metadata:
  name: fn2							  name: fn2
spec:								spec:
  name: fn2							  name: fn2
  image: fn2:latest						  image: fn2:latest
---								---
apiVersion: openfaas.com/v1					apiVersion: openfaas.com/v1
kind: Function							kind: Function
metadata:							metadata:
  name: fn20							  name: fn20
spec:								spec:
  name: fn20							  name: fn20
  image: fn20:latest						  image: fn20:latest
---								---
apiVersion: openfaas.com/v1					apiVersion: openfaas.com/v1
kind: Function							kind: Function
metadata:							metadata:
  name: fn3							  name: fn3
spec:								spec:
  name: fn3							  name: fn3
  image: fn3:latest						  image: fn3:latest
---								---
apiVersion: openfaas.com/v1					apiVersion: openfaas.com/v1
kind: Function							kind: Function
metadata:							metadata:
  name: fn4							  name: fn4
spec:								spec:
  name: fn4							  name: fn4
  image: fn4:latest						  image: fn4:latest
---								---
apiVersion: openfaas.com/v1					apiVersion: openfaas.com/v1
kind: Function							kind: Function
metadata:							metadata:
  name: fn5							  name: fn5
spec:								spec:
  name: fn5							  name: fn5
  image: fn5:latest						  image: fn5:latest
---								---
apiVersion: openfaas.com/v1					apiVersion: openfaas.com/v1
kind: Function							kind: Function
metadata:							metadata:
  name: fn6							  name: fn6
spec:								spec:
  name: fn6							  name: fn6
  image: fn6:latest						  image: fn6:latest
---								---
apiVersion: openfaas.com/v1					apiVersion: openfaas.com/v1
kind: Function							kind: Function
metadata:							metadata:
  name: fn7							  name: fn7
spec:								spec:
  name: fn7							  name: fn7
  image: fn7:latest						  image: fn7:latest
---								---
apiVersion: openfaas.com/v1					apiVersion: openfaas.com/v1
kind: Function							kind: Function
metadata:							metadata:
  name: fn8							  name: fn8
spec:								spec:
  name: fn8							  name: fn8
  image: fn8:latest						  image: fn8:latest
---								---
apiVersion: openfaas.com/v1					apiVersion: openfaas.com/v1
kind: Function							kind: Function
metadata:							metadata:
  name: fn9							  name: fn9
spec:								spec:
  name: fn9							  name: fn9
  image: fn9:latest						  image: fn9:latest
```
* For completeness perform same steps with --api serving.knative.dev/v1
```
mkdir generated3
$ for i in {1..20}; do faas-cli generate --api serving.knative.dev/v1  -f fn1.yml > ./generated3/$i.yml ; done
$ ls generated3                                                                                      
1.yml	10.yml	11.yml	12.yml	13.yml	14.yml	15.yml	16.yml	17.yml	18.yml	19.yml	2.yml	20.yml	3.yml	4.yml	5.yml	6.yml	7.yml	8.yml	9.yml
$ cd generated3                                                                                                                   
$ for i in {1..20}; do for j in {1..20}; do cmp -b $i.yml $j.yml >> diffs.txt ; done ; done                                       
$ cat diffs.txt                                                                                                                   
$ diff -y -W 120  1.yml 2.yml                                                                                                     
---								---
apiVersion: serving.knative.dev/v1				apiVersion: serving.knative.dev/v1
kind: Service							kind: Service
metadata:							metadata:
  name: fn1							  name: fn1
spec:								spec:
  template:							  template:
    spec:							    spec:
      containers:						      containers:
      - image: fn1:latest					      - image: fn1:latest
---								---
apiVersion: serving.knative.dev/v1				apiVersion: serving.knative.dev/v1
kind: Service							kind: Service
metadata:							metadata:
  name: fn10							  name: fn10
spec:								spec:
  template:							  template:
    spec:							    spec:
      containers:						      containers:
      - image: fn10:latest					      - image: fn10:latest
---								---
apiVersion: serving.knative.dev/v1				apiVersion: serving.knative.dev/v1
kind: Service							kind: Service
metadata:							metadata:
  name: fn11							  name: fn11
spec:								spec:
  template:							  template:
    spec:							    spec:
      containers:						      containers:
      - image: fn11:latest					      - image: fn11:latest
---								---
apiVersion: serving.knative.dev/v1				apiVersion: serving.knative.dev/v1
kind: Service							kind: Service
metadata:							metadata:
  name: fn12							  name: fn12
spec:								spec:
  template:							  template:
    spec:							    spec:
      containers:						      containers:
      - image: fn12:latest					      - image: fn12:latest
---								---
apiVersion: serving.knative.dev/v1				apiVersion: serving.knative.dev/v1
kind: Service							kind: Service
metadata:							metadata:
  name: fn13							  name: fn13
spec:								spec:
  template:							  template:
    spec:							    spec:
      containers:						      containers:
      - image: fn13:latest					      - image: fn13:latest
---								---
apiVersion: serving.knative.dev/v1				apiVersion: serving.knative.dev/v1
kind: Service							kind: Service
metadata:							metadata:
  name: fn14							  name: fn14
spec:								spec:
  template:							  template:
    spec:							    spec:
      containers:						      containers:
      - image: fn14:latest					      - image: fn14:latest
---								---
apiVersion: serving.knative.dev/v1				apiVersion: serving.knative.dev/v1
kind: Service							kind: Service
metadata:							metadata:
  name: fn15							  name: fn15
spec:								spec:
  template:							  template:
    spec:							    spec:
      containers:						      containers:
      - image: fn15:latest					      - image: fn15:latest
---								---
apiVersion: serving.knative.dev/v1				apiVersion: serving.knative.dev/v1
kind: Service							kind: Service
metadata:							metadata:
  name: fn16							  name: fn16
spec:								spec:
  template:							  template:
    spec:							    spec:
      containers:						      containers:
      - image: fn16:latest					      - image: fn16:latest
---								---
apiVersion: serving.knative.dev/v1				apiVersion: serving.knative.dev/v1
kind: Service							kind: Service
metadata:							metadata:
  name: fn17							  name: fn17
spec:								spec:
  template:							  template:
    spec:							    spec:
      containers:						      containers:
      - image: fn17:latest					      - image: fn17:latest
---								---
apiVersion: serving.knative.dev/v1				apiVersion: serving.knative.dev/v1
kind: Service							kind: Service
metadata:							metadata:
  name: fn18							  name: fn18
spec:								spec:
  template:							  template:
    spec:							    spec:
      containers:						      containers:
      - image: fn18:latest					      - image: fn18:latest
---								---
apiVersion: serving.knative.dev/v1				apiVersion: serving.knative.dev/v1
kind: Service							kind: Service
metadata:							metadata:
  name: fn19							  name: fn19
spec:								spec:
  template:							  template:
    spec:							    spec:
      containers:						      containers:
      - image: fn19:latest					      - image: fn19:latest
---								---
apiVersion: serving.knative.dev/v1				apiVersion: serving.knative.dev/v1
kind: Service							kind: Service
metadata:							metadata:
  name: fn2							  name: fn2
spec:								spec:
  template:							  template:
    spec:							    spec:
      containers:						      containers:
      - image: fn2:latest					      - image: fn2:latest
---								---
apiVersion: serving.knative.dev/v1				apiVersion: serving.knative.dev/v1
kind: Service							kind: Service
metadata:							metadata:
  name: fn20							  name: fn20
spec:								spec:
  template:							  template:
    spec:							    spec:
      containers:						      containers:
      - image: fn20:latest					      - image: fn20:latest
---								---
apiVersion: serving.knative.dev/v1				apiVersion: serving.knative.dev/v1
kind: Service							kind: Service
metadata:							metadata:
  name: fn3							  name: fn3
spec:								spec:
  template:							  template:
    spec:							    spec:
      containers:						      containers:
      - image: fn3:latest					      - image: fn3:latest
---								---
apiVersion: serving.knative.dev/v1				apiVersion: serving.knative.dev/v1
kind: Service							kind: Service
metadata:							metadata:
  name: fn4							  name: fn4
spec:								spec:
  template:							  template:
    spec:							    spec:
      containers:						      containers:
      - image: fn4:latest					      - image: fn4:latest
---								---
apiVersion: serving.knative.dev/v1				apiVersion: serving.knative.dev/v1
kind: Service							kind: Service
metadata:							metadata:
  name: fn5							  name: fn5
spec:								spec:
  template:							  template:
    spec:							    spec:
      containers:						      containers:
      - image: fn5:latest					      - image: fn5:latest
---								---
apiVersion: serving.knative.dev/v1				apiVersion: serving.knative.dev/v1
kind: Service							kind: Service
metadata:							metadata:
  name: fn6							  name: fn6
spec:								spec:
  template:							  template:
    spec:							    spec:
      containers:						      containers:
      - image: fn6:latest					      - image: fn6:latest
---								---
apiVersion: serving.knative.dev/v1				apiVersion: serving.knative.dev/v1
kind: Service							kind: Service
metadata:							metadata:
  name: fn7							  name: fn7
spec:								spec:
  template:							  template:
    spec:							    spec:
      containers:						      containers:
      - image: fn7:latest					      - image: fn7:latest
---								---
apiVersion: serving.knative.dev/v1				apiVersion: serving.knative.dev/v1
kind: Service							kind: Service
metadata:							metadata:
  name: fn8							  name: fn8
spec:								spec:
  template:							  template:
    spec:							    spec:
      containers:						      containers:
      - image: fn8:latest					      - image: fn8:latest
---								---
apiVersion: serving.knative.dev/v1				apiVersion: serving.knative.dev/v1
kind: Service							kind: Service
metadata:							metadata:
  name: fn9							  name: fn9
spec:								spec:
  template:							  template:
    spec:							    spec:
      containers:						      containers:
      - image: fn9:latest					      - image: fn9:latest
```

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
The ordering of functions seems like it would be helpful.

I am sure whether this is enough to suppress a diff, given that we have maps of labels and annotations, which have a non deterministic order. Can you show an example with these fields?

**Comment by rgee0** [comment]
* For completeness perform same steps with --api serving.knative.dev/v1.  Initial test found a difference around how environment variable are handled.  Second commit accommodates this

```
$ faas-cli version
  ___                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|

CLI:
 commit:  b7c88c82ec56c0be512f0faa7e77294b8a99b808-dirty
 version: 0.6.13-366-gb7c88c82
Your faas-cli version (0.6.13-366-gb7c88c82) may be out of date. Version: 0.13.9 is now available on GitHub.

$ for i in {1..20}; do faas-cli generate --api serving.knative.dev/v1  -f fn1.yml > ./generated5/$i.yml ; done

$ ls generated5                                                                                                                   
1.yml	10.yml	11.yml	12.yml	13.yml	14.yml	15.yml	16.yml	17.yml	18.yml	19.yml	2.yml	20.yml	3.yml	4.yml	5.yml	6.yml	7.yml	8.yml	9.yml

$ cd generated5                                                                                                                   

$ for i in {1..20}; do for j in {1..20}; do cmp -b $i.yml $j.yml >> diffs.txt ; done ; done                                       
$ cat diffs.txt                                                                                                                   

$ diff -y -W 120  1.yml 2.yml                                                                                                     
---								---
apiVersion: serving.knative.dev/v1				apiVersion: serving.knative.dev/v1
kind: Service							kind: Service
metadata:							metadata:
  name: fn1							  name: fn1
spec:								spec:
  template:							  template:
    spec:							    spec:
      containers:						      containers:
      - image: fn1:latest					      - image: fn1:latest
---								---
apiVersion: serving.knative.dev/v1				apiVersion: serving.knative.dev/v1
kind: Service							kind: Service
metadata:							metadata:
  name: fn10							  name: fn10
spec:								spec:
  template:							  template:
    spec:							    spec:
      containers:						      containers:
      - image: fn10:latest					      - image: fn10:latest
---								---
apiVersion: serving.knative.dev/v1				apiVersion: serving.knative.dev/v1
kind: Service							kind: Service
metadata:							metadata:
  name: fn11							  name: fn11
spec:								spec:
  template:							  template:
    spec:							    spec:
      containers:						      containers:
      - image: fn11:latest					      - image: fn11:latest
---								---
apiVersion: serving.knative.dev/v1				apiVersion: serving.knative.dev/v1
kind: Service							kind: Service
metadata:							metadata:
  name: fn12							  name: fn12
spec:								spec:
  template:							  template:
    spec:							    spec:
      containers:						      containers:
      - image: fn12:latest					      - image: fn12:latest
---								---
apiVersion: serving.knative.dev/v1				apiVersion: serving.knative.dev/v1
kind: Service							kind: Service
metadata:							metadata:
  name: fn13							  name: fn13
spec:								spec:
  template:							  template:
    spec:							    spec:
      containers:						      containers:
      - image: fn13:latest					      - image: fn13:latest
---								---
apiVersion: serving.knative.dev/v1				apiVersion: serving.knative.dev/v1
kind: Service							kind: Service
metadata:							metadata:
  name: fn14							  name: fn14
spec:								spec:
  template:							  template:
    spec:							    spec:
      containers:						      containers:
      - image: fn14:latest					      - image: fn14:latest
---								---
apiVersion: serving.knative.dev/v1				apiVersion: serving.knative.dev/v1
kind: Service							kind: Service
metadata:							metadata:
  name: fn15							  name: fn15
spec:								spec:
  template:							  template:
    spec:							    spec:
      containers:						      containers:
      - image: fn15:latest					      - image: fn15:latest
---								---
apiVersion: serving.knative.dev/v1				apiVersion: serving.knative.dev/v1
kind: Service							kind: Service
metadata:							metadata:
  name: fn16							  name: fn16
spec:								spec:
  template:							  template:
    spec:							    spec:
      containers:						      containers:
      - image: fn16:latest					      - image: fn16:latest
---								---
apiVersion: serving.knative.dev/v1				apiVersion: serving.knative.dev/v1
kind: Service							kind: Service
metadata:							metadata:
  name: fn17							  name: fn17
spec:								spec:
  template:							  template:
    spec:							    spec:
      containers:						      containers:
      - image: fn17:latest					      - image: fn17:latest
---								---
apiVersion: serving.knative.dev/v1				apiVersion: serving.knative.dev/v1
kind: Service							kind: Service
metadata:							metadata:
  name: fn18							  name: fn18
spec:								spec:
  template:							  template:
    spec:							    spec:
      containers:						      containers:
      - image: fn18:latest					      - image: fn18:latest
---								---
apiVersion: serving.knative.dev/v1				apiVersion: serving.knative.dev/v1
kind: Service							kind: Service
metadata:							metadata:
  name: fn19							  name: fn19
spec:								spec:
  template:							  template:
    spec:							    spec:
      containers:						      containers:
      - image: fn19:latest					      - image: fn19:latest
---								---
apiVersion: serving.knative.dev/v1				apiVersion: serving.knative.dev/v1
kind: Service							kind: Service
metadata:							metadata:
  name: fn2							  name: fn2
  annotations:							  annotations:
    com.openfaas.health.http.initialDelay: 30s			    com.openfaas.health.http.initialDelay: 30s
    com.openfaas.health.http.path: /healthz			    com.openfaas.health.http.path: /healthz
    expire-date: Wed Aug  8 07:40:18 BST 2018			    expire-date: Wed Aug  8 07:40:18 BST 2018
    topic: kafka.payments-received				    topic: kafka.payments-received
spec:								spec:
  template:							  template:
    spec:							    spec:
      containers:						      containers:
      - image: fn2:latest					      - image: fn2:latest
---								---
apiVersion: serving.knative.dev/v1				apiVersion: serving.knative.dev/v1
kind: Service							kind: Service
metadata:							metadata:
  name: fn20							  name: fn20
spec:								spec:
  template:							  template:
    spec:							    spec:
      containers:						      containers:
      - image: fn20:latest					      - image: fn20:latest
---								---
apiVersion: serving.knative.dev/v1				apiVersion: serving.knative.dev/v1
kind: Service							kind: Service
metadata:							metadata:
  name: fn3							  name: fn3
spec:								spec:
  template:							  template:
    spec:							    spec:
      containers:						      containers:
      - image: fn3:latest					      - image: fn3:latest
        env:							        env:
        - name: env1						        - name: env1
          value: val1						          value: val1
        - name: env2						        - name: env2
          value: val2						          value: val2
        - name: env3						        - name: env3
          value: val3						          value: val3
        - name: include_images					        - name: include_images
          value: key2						          value: key2
        - name: rss_feed_url					        - name: rss_feed_url
          value: key1						          value: key1
---								---
apiVersion: serving.knative.dev/v1				apiVersion: serving.knative.dev/v1
kind: Service							kind: Service
metadata:							metadata:
  name: fn4							  name: fn4
spec:								spec:
  template:							  template:
    spec:							    spec:
      containers:						      containers:
      - image: fn4:latest					      - image: fn4:latest
---								---
apiVersion: serving.knative.dev/v1				apiVersion: serving.knative.dev/v1
kind: Service							kind: Service
metadata:							metadata:
  name: fn5							  name: fn5
spec:								spec:
  template:							  template:
    spec:							    spec:
      containers:						      containers:
      - image: fn5:latest					      - image: fn5:latest
---								---
apiVersion: serving.knative.dev/v1				apiVersion: serving.knative.dev/v1
kind: Service							kind: Service
metadata:							metadata:
  name: fn6							  name: fn6
spec:								spec:
  template:							  template:
    spec:							    spec:
      containers:						      containers:
      - image: fn6:latest					      - image: fn6:latest
---								---
apiVersion: serving.knative.dev/v1				apiVersion: serving.knative.dev/v1
kind: Service							kind: Service
metadata:							metadata:
  name: fn7							  name: fn7
spec:								spec:
  template:							  template:
    spec:							    spec:
      containers:						      containers:
      - image: fn7:latest					      - image: fn7:latest
---								---
apiVersion: serving.knative.dev/v1				apiVersion: serving.knative.dev/v1
kind: Service							kind: Service
metadata:							metadata:
  name: fn8							  name: fn8
spec:								spec:
  template:							  template:
    spec:							    spec:
      containers:						      containers:
      - image: fn8:latest					      - image: fn8:latest
---								---
apiVersion: serving.knative.dev/v1				apiVersion: serving.knative.dev/v1
kind: Service							kind: Service
metadata:							metadata:
  name: fn9							  name: fn9
spec:								spec:
  template:							  template:
    spec:							    spec:
      containers:						      containers:
      - image: fn9:latest					      - image: fn9:latest
```

**Comment by rgee0** [comment]
@brandonkal does this address your use case?

**Comment by rgee0** [comment]
I'll close this owing to lack of interest.  Also suggest #777 is no longer an issue and can be closed.  Will add a note over there.

**Comment by alexellis** [comment]
@rgee0 I would not read too much into whether there is interest from someone not replying.

> I am not sure whether this is enough to suppress a diff, given that we have maps of labels and annotations, which have a non deterministic order. 

Did you find an answer to my questions on the ordering of maps in go? The output was a bit overwhelming, a brief summary or a unit test that can be run with an amount flag would be easier to digest i.e. `go test -count=100`

**Comment by rgee0** [comment]
The order of annotations and labels is already deterministic owing to how 'yaml.Marshal' works with `map[string]string`.  This means that the default generate was already predictable, as show in the testing in https://github.com/openfaas/faas-cli/pull/873#issuecomment-797670855

A slight difference was found in `--api serving.knative.dev/v1` whereby the env pairs were not being sorted - related to the type involved, I believe.  This was addressed in the second commit and demonstrated in https://github.com/openfaas/faas-cli/pull/873#issuecomment-797671807

**Comment by alexellis** [comment]
That's helpful. I hope you can see how several pages of text output makes it hard to see the wood for the trees.

Could you re-open your PR please?

**Review by alexellis — APPROVED** [review]
Approved

**Comment by alexellis** [comment]
Thank you for persevering with this PR and for explaining it to me :slightly_smiling_face:

**Comment by alexellis** [comment]
@rgee0 I've just contributed #891 which adds annotation support (which was previously missed) - do you need to send a PR to order the annotation output, would you mind looking into this?

**Comment by rgee0** [comment]
Looked into this and for the OpenFaaS CR generation and the existing work also accommodates the changes made in #891 to add annotations.  The annotations are now present and their ordering is deterministic.

## Test output using similar `fn1.yml` input file as shown above
* Run generate multiple times to create a sample set
```
$ for i in {1..20}; do faas-cli generate  -f fn1.yml > ./generated/$i.yml ; done
```
* Move into the generated output and check there are 20 files
```
$ cd generated
$ ls
1.yml		12.yml		15.yml		18.yml		20.yml		5.yml		8.yml
10.yml		13.yml		16.yml		19.yml		3.yml		6.yml		9.yml
11.yml		14.yml		17.yml		2.yml		4.yml		7.yml
```
* Compare each of the pairs of files and inspect output
```
$ for i in {1..20}; do for j in {1..20}; do cmp -b $i.yml $j.yml >> diffs.txt ; done ; done

$ cat diffs.txt
```
* Compare two of the files to double check `cmp` output
```
$ diff -y -W 120  1.yml 2.yml
---								---
apiVersion: openfaas.com/v1					apiVersion: openfaas.com/v1
kind: Function							kind: Function
metadata:							metadata:
  name: fn1							  name: fn1
spec:								spec:
  name: fn1							  name: fn1
  image: fn1:latest						  image: fn1:latest
  labels:							  labels:
    label1: "true"						    label1: "true"
    label2: "false"						    label2: "false"
    label3: fred						    label3: fred
    label4: burt						    label4: burt
---								---
apiVersion: openfaas.com/v1					apiVersion: openfaas.com/v1
kind: Function							kind: Function
metadata:							metadata:
  name: fn10							  name: fn10
spec:								spec:
  name: fn10							  name: fn10
  image: fn10:latest						  image: fn10:latest
---								---
apiVersion: openfaas.com/v1					apiVersion: openfaas.com/v1
kind: Function							kind: Function
metadata:							metadata:
  name: fn11							  name: fn11
spec:								spec:
  name: fn11							  name: fn11
  image: fn11:latest						  image: fn11:latest
---								---
apiVersion: openfaas.com/v1					apiVersion: openfaas.com/v1
kind: Function							kind: Function
metadata:							metadata:
  name: fn12							  name: fn12
spec:								spec:
  name: fn12							  name: fn12
  image: fn12:latest						  image: fn12:latest
---								---
apiVersion: openfaas.com/v1					apiVersion: openfaas.com/v1
kind: Function							kind: Function
metadata:							metadata:
  name: fn13							  name: fn13
spec:								spec:
  name: fn13							  name: fn13
  image: fn13:latest						  image: fn13:latest
---								---
apiVersion: openfaas.com/v1					apiVersion: openfaas.com/v1
kind: Function							kind: Function
metadata:							metadata:
  name: fn14							  name: fn14
spec:								spec:
  name: fn14							  name: fn14
  image: fn14:latest						  image: fn14:latest
---								---
apiVersion: openfaas.com/v1					apiVersion: openfaas.com/v1
kind: Function							kind: Function
metadata:							metadata:
  name: fn15							  name: fn15
spec:								spec:
  name: fn15							  name: fn15
  image: fn15:latest						  image: fn15:latest
---								---
apiVersion: openfaas.com/v1					apiVersion: openfaas.com/v1
kind: Function							kind: Function
metadata:							metadata:
  name: fn16							  name: fn16
spec:								spec:
  name: fn16							  name: fn16
  image: fn16:latest						  image: fn16:latest
---								---
apiVersion: openfaas.com/v1					apiVersion: openfaas.com/v1
kind: Function							kind: Function
metadata:							metadata:
  name: fn17							  name: fn17
spec:								spec:
  name: fn17							  name: fn17
  image: fn17:latest						  image: fn17:latest
---								---
apiVersion: openfaas.com/v1					apiVersion: openfaas.com/v1
kind: Function							kind: Function
metadata:							metadata:
  name: fn18							  name: fn18
spec:								spec:
  name: fn18							  name: fn18
  image: fn18:latest						  image: fn18:latest
---								---
apiVersion: openfaas.com/v1					apiVersion: openfaas.com/v1
kind: Function							kind: Function
metadata:							metadata:
  name: fn19							  name: fn19
spec:								spec:
  name: fn19							  name: fn19
  image: fn19:latest						  image: fn19:latest
---								---
apiVersion: openfaas.com/v1					apiVersion: openfaas.com/v1
kind: Function							kind: Function
metadata:							metadata:
  name: fn2							  name: fn2
spec:								spec:
  name: fn2							  name: fn2
  image: fn2:latest						  image: fn2:latest
  annotations:							  annotations:
    com.openfaas.health.http.initialDelay: 30s			    com.openfaas.health.http.initialDelay: 30s
    com.openfaas.health.http.path: /healthz			    com.openfaas.health.http.path: /healthz
    expire-date: Wed Aug  8 07:40:18 BST 2018			    expire-date: Wed Aug  8 07:40:18 BST 2018
    topic: kafka.payments-received				    topic: kafka.payments-received
---								---
apiVersion: openfaas.com/v1					apiVersion: openfaas.com/v1
kind: Function							kind: Function
metadata:							metadata:
  name: fn20							  name: fn20
spec:								spec:
  name: fn20							  name: fn20
  image: fn20:latest						  image: fn20:latest
---								---
apiVersion: openfaas.com/v1					apiVersion: openfaas.com/v1
kind: Function							kind: Function
metadata:							metadata:
  name: fn3							  name: fn3
spec:								spec:
  name: fn3							  name: fn3
  image: fn3:latest						  image: fn3:latest
  environment:							  environment:
    env1: val1							    env1: val1
    env2: val2							    env2: val2
    env3: val3							    env3: val3
    include_images: key2					    include_images: key2
    rss_feed_url: key1						    rss_feed_url: key1
---								---
apiVersion: openfaas.com/v1					apiVersion: openfaas.com/v1
kind: Function							kind: Function
metadata:							metadata:
  name: fn4							  name: fn4
spec:								spec:
  name: fn4							  name: fn4
  image: fn4:latest						  image: fn4:latest
---								---
apiVersion: openfaas.com/v1					apiVersion: openfaas.com/v1
kind: Function							kind: Function
metadata:							metadata:
  name: fn5							  name: fn5
spec:								spec:
  name: fn5							  name: fn5
  image: fn5:latest						  image: fn5:latest
---								---
apiVersion: openfaas.com/v1					apiVersion: openfaas.com/v1
kind: Function							kind: Function
metadata:							metadata:
  name: fn6							  name: fn6
spec:								spec:
  name: fn6							  name: fn6
  image: fn6:latest						  image: fn6:latest
---								---
apiVersion: openfaas.com/v1					apiVersion: openfaas.com/v1
kind: Function							kind: Function
metadata:							metadata:
  name: fn7							  name: fn7
spec:								spec:
  name: fn7							  name: fn7
  image: fn7:latest						  image: fn7:latest
---								---
apiVersion: openfaas.com/v1					apiVersion: openfaas.com/v1
kind: Function							kind: Function
metadata:							metadata:
  name: fn8							  name: fn8
spec:								spec:
  name: fn8							  name: fn8
  image: fn8:latest						  image: fn8:latest
---								---
apiVersion: openfaas.com/v1					apiVersion: openfaas.com/v1
kind: Function							kind: Function
metadata:							metadata:
  name: fn9							  name: fn9
spec:								spec:
  name: fn9							  name: fn9
  image: fn9:latest						  image: fn9:latest

```

Order of functions and their attributes are consistent across the two files

**Pull request merged**
