### PR TITLE
ci: standardize Github Actions

### PR DESCRIPTION
**Pull request by cpanato**
## Description
This Pr tries to make the CI jobs similar to the others in Org.

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))
Related to https://github.com/openfaas/faas/issues/1643

## How Has This Been Tested?
UPDATE:

- Merged this PR in my fork and then created a tag `0.99.999`
- create a release based on the tag that was created
- the publish GitHub will push the images + binaries
- The release can be found here: 
  - execution: https://github.com/cpanato/faas-cli/runs/3645225532?check_suite_focus=true
  - release: https://github.com/cpanato/faas-cli/releases/tag/0.99.999

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

/assign @alexellis

### CODE REVIEW

**Comment by alexellis** [comment]
Same comment as on:

https://github.com/openfaas/faas-netes/pull/785#pullrequestreview-750116550

> This cannot be merged until we add the `permissions` section, please see: https://github.com/openfaas/ingress-operator/blob/master/.github/workflows/publish.yaml#L11 

Only change the publish step though, as the build should not do any pushes of images, so doesn't need write access to packages.

**Comment by cpanato** [comment]
done here as well, PTAL @alexellis

**Comment by alexellis** [comment]
> How Has This Been Tested?

This was left blank, so can you please cut a release on your fork and show that all the binaries are uploaded and the container were created as expected?

Why is testing important? If not, and I cut a release, users will be confused seeing a release with no binaries or corresponding container images.

**Comment by cpanato** [comment]
> > How Has This Been Tested?
> 
> This was left blank, so can you please cut a release on your fork and show that all the binaries are uploaded and the container were created as expected?
> 
> Why is testing important? If not, and I cut a release, users will be confused seeing a release with no binaries or corresponding container images.

@alexellis done, update the PR summary to add the test part. PTAL

**Comment by alexellis** [comment]
Thanks, we went in a different direction so closing now.

**Pull request closed without merging**
