### PR TITLE
Add annotations to revisionTemplate for knative

### PR DESCRIPTION
**Pull request by alexellis**
Signed-off-by: Alex Ellis (OpenFaaS Ltd) <alexellis2@gmail.com>

Add annotations to revisionTemplate for knative

## Description

* Adds metadata to the knative spec in the generation command

## Motivation and Context

* Fixes: #815

## How Has This Been Tested?

```
Tested by running locally and verifying it matched the request
from @Jeff-Lowrey

faas-cli generate \
  --api=serving.knative.dev/v1alpha1 \
  --annotation sidecar.istio.io/inject=true

This also works when bringing in annotations from the YAML
file.
```

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Can you try this example please Jeff?

```yaml
---
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: nodeinfo
spec:
  runLatest:
    configuration:
      revisionTemplate:
        metadata:
          annotations:
            sidecar.istio.io/inject: "true"
        spec:
          container:
            image: functions/nodeinfo-http:latest
```

**Comment by alexellis** [comment]
I tested this e2e with Knative and inlets-operator (PRO) and was able to access NodeInfo as expected, no errors and the ksvc gave the following:

```
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      creationTimestamp: null
    spec:
      containerConcurrency: 0
      containers:
      - image: functions/nodeinfo-http:latest
        name: user-container
        readinessProbe:
          successThreshold: 1
          tcpSocket:
            port: 0
        resources: {}
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
```

**Comment by Jeff-Lowrey** [comment]
Not sure what I'm doing wrong here,

Pull the PR:

```
JLOWREY MINGW64 ~
$ git clone https://github.com/openfaas/faas-cli
Cloning into 'faas-cli'...
remote: Enumerating objects: 73, done.
remote: Counting objects: 100% (73/73), done.
remote: Compressing objects: 100% (55/55), done.
remote: Total 16056 (delta 35), reused 23 (delta 16), pack-reused 15983
Receiving objects: 100% (16056/16056), 18.72 MiB | 2.80 MiB/s, done.
Resolving deltas: 100% (5046/5046), done.
Updating files: 100% (729/729), done.

JLOWREY MINGW64 ~
$ cd faas-cli/

JLOWREY MINGW64 ~/faas-cli (master)
$ gh pr checkout 816
Switched to a new branch 'openfaasltd/extend-knative-fix-815'

```

Build the client:

```
JLOWREY MINGW64 ~/faas-cli (openfaasltd/extend-knative-fix-815)

JLOWREY MINGW64 ~/faas-cli (openfaasltd/extend-knative-fix-815)
$ go build .

```

Try to run it a few different ways, same result:

```

JLOWREY MINGW64 ~/faas-cli (openfaasltd/extend-knative-fix-815)
$ faas-cli.exe generate --api=serving.knative.dev/v1alpha1 --annotation sidecar.istio.io/inject=true
Unknown flag: --annotation

JLOWREY MINGW64 ~/faas-cli (openfaasltd/extend-knative-fix-815)
$ go run . generate --api=serving.knative.dev/v1alpha1 --annotation sidecar.istio.io/inject=true
Unknown flag: --annotation
exit status 1

```

Confirm I have the right code:

```

JLOWREY MINGW64 ~/faas-cli (openfaasltd/extend-knative-fix-815)
$ head -50 commands/generate.go
// Copyright (c) OpenFaaS Author(s) 2018. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

package commands

import (
        "fmt"

        v2 "github.com/openfaas/faas-cli/schema/store/v2"

        "github.com/openfaas/faas-cli/builder"
        "github.com/openfaas/faas-cli/proxy"
        "github.com/openfaas/faas-cli/schema"
        knativev1alpha1 "github.com/openfaas/faas-cli/schema/knative/v1alpha1"
        openfaasv1alpha2 "github.com/openfaas/faas-cli/schema/openfaas/v1alpha2"
        "github.com/openfaas/faas-cli/stack"
        "github.com/pkg/errors"
        "github.com/spf13/cobra"
        yaml "gopkg.in/yaml.v2"
)

const (
        defaultFunctionNamespace = "openfaas-fn"
        resourceKind             = "Function"
        defaultAPIVersion        = "openfaas.com/v1alpha2"
)

var (
        api               string
        functionNamespace string
        fromStore         string
        desiredArch       string
        annotationArgs    []string
)

func init() {

        generateCmd.Flags().StringVar(&fromStore, "from-store", "", "generate using a store image")

        generateCmd.Flags().StringVar(&api, "api", defaultAPIVersion, "CRD API version e.g openfaas.com/v1alpha2, serving.knative.dev/v1alpha1")
        generateCmd.Flags().StringVarP(&functionNamespace, "namespace", "n", defaultFunctionNamespace, "Kubernetes namespace for functions")
        generateCmd.Flags().Var(&tagFormat, "tag", "Override latest tag on function Docker image, accepts 'latest', 'sha', 'branch', 'describe'")
        generateCmd.Flags().BoolVar(&envsubst, "envsubst", true, "Substitute environment variables in stack.yml file")
        generateCmd.Flags().StringVar(&desiredArch, "arch", "x86_64", "Desired image arch. (Default x86_64)")
        generateCmd.Flags().StringArrayVar(&annotationArgs, "annotation", []string{}, "Any annotations you want to add")

        faasCmd.AddCommand(generateCmd)
}

var generateCmd = &cobra.Command{

```
Maybe I'm running it wrong? Maybe I'm building it wrong?

**Comment by alexellis** [comment]
Can you try running the YAML example that I generated and pasted here?

**Pull request merged**
