### PR TITLE
fix the bug with build operation in faas-cli for docker versions 23.0.0 and above

### PR DESCRIPTION
**Pull request by NikhilSharmaWe**
## Description

For docker versions `23.0.0` and above the env var `DOCKER_BUILDKIT` is equal to 1 by default for using the docker build kit, which used `docker buildx build` instead of `docker build`. This PR fixes the bug with the faas-cli build operation and docker build for docker version 23.0.0 and above. PTAL: #958 for more info.

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))
Fixes: #958
## How Has This Been Tested?

I have tested the changes. Now the `faas-cli build` works fine also with docker version `23.0.0` and above.
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by NikhilSharmaWe** [comment]
I think then we can update the build to also use `buildx build` command as publish and set `DOCKER_BUILDKIT` to 1 in all cases.
WDYT?

**Comment by alexellis** [comment]
The `buildx build` command cannot be used, since it requires a specific modern docker version, right?

But what is the issue with `DOCKER_BUILDKIT=1 docker build`?

**Comment by NikhilSharmaWe** [comment]
If we set DOCKER_BUILDKIT=1 then `docker buildx build` is used instead of `docker build`, so that won't work for build in faas-cli, since it uses `docker build` unlike publish which uses `docker buildx build`.

**Comment by alexellis** [comment]
> @alexellis If we set DOCKER_BUILDKIT=1 then docker buildx build is used instead of docker build, so that won't work for build in faas-cli, since it uses docker build unlike publish which uses docker buildx build.

I often set `DOCKER_BUILDKIT=1` and it does work for me - same for @welteki 

Perhaps you need to run `docker buildx install`? `uninstall` reverts that change.

**Comment by NikhilSharmaWe** [comment]
@alexellis
- After `docker buildx uninstall`, it works. Could be that the `docker buildx` and docker engine I installed were installed separately. Not sure.

- Also, should we add a `--buildkit=true` flag or `DOCKER_BUILDKIT=1 faas-cli build` is fine for now.

**Pull request closed without merging**
