### PR TITLE
Added F# template to list.

### PR DESCRIPTION
**Pull request by hayer**
## Description
I am by no means a f# genius so suggestions/tips/wishes are welcome. The template is based on the C# one.

## Motivation and Context
I've recently started using Open FaaS and wanted to use it with F#. There was no template for F# that I could find so I made one.

Related to issue #276 

## How Has This Been Tested?
Tested with a minimal Hello World function and some others. 
 * Created function with template
 * Added the output "Hello, functional world!"
 * Called the function in my browser.

## Types of changes
None apply
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [ ] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by hayer** [comment]
First pull-request so please tell me if there are so obvious issues I should fix.

About the signing of commits, I haven't signed the ones in my repository. Knew this was a thing, but hadn't looked into it before now - and I it seems kinda troublesome to sign commits that has already been pushed..

**Comment by alexellis** [comment]
Hi there - welcome to the community!

Derek is talking about the commit to this repository. The easiest way to make the change may be for you to read the contribution guide and do a new PR in a new branch. I'll need to test the template and review it before linking out.

Glad you are enjoying using OpenFaaS

**Comment by hayer** [comment]
Okay, so I'll try that. Please bear with me. English isn't my native language so I might have missed some details on what to sign where.

@alexellis After looking at some of the other commits it the commit changing the README.md that I have to sign, correct? Or do I need to change anything in my template repository?

**Comment by alexellis** [comment]
I can see you're still having trouble. Simply to sign off a commit put `git commit -s -m "Message goes here"` and if you forget then do `git commit -s -m "Message here" --amend` followed by a `git push --force`.

I will add the change to the readme on your behalf after testing the template later this week.

**Comment by alexellis** [comment]
PR #344 merges your change but needs action on your repo first.

**Pull request closed without merging**
