### PR TITLE
Use core.autocrlf false when cloning templates

### LINKED ISSUE #551: Template fetching has line-endings overridden by git config (breaks function build on Windows)
## Expected Behaviour

Templates pulled via `faas new` or `faas template pull` should have the same line endings as committed in the openfaas/templates repo.

## Current Behaviour

Currently the fetch code in `faas-cli` doesn't attempt to override any user settings of `core.autocrlf` which results in function builds working for some users and failing for others depending on whether it has been set to `true` or `false`, for example:
- User on Windows with `core.autocrlf = true` will see failures building with the Go template as files are transferred to the build context with altered `CRLF` line endings.
- User on OSX/Linux with `core.autocrlf = true` will see files committed with `CRLF` line-endings transferred to the build context with the unix `LF` line-ending.

This has caused confusion for both users and community members trying to remotely diagnose whats going on where they don't have awareness of the differing behaviour on Windows.

## Possible Solution

Override any user/environment settings when cloning the templates repository within the command.

## Steps to Reproduce (for bugs)

1. The following steps should be carried out on Windows, behaviour is unchanged on Linux/OSX
2. `git config core.autocrlf true`
3. `faas new myfn --lang go`
4. `faas build -f myfn.yml`
5. Previous command will error out complaining that `gofmt -w -s` must be run.
6. `cd <some temp dir>`
7. `faas template pull`
8. Check the line endings of files in the `template\go` dir, you should see `CRLF` line endings (changed from `LF`)

## Context

Macbook-less for another week so on a Windows 10 Surface Pro 4, had encountered problems building Go functions caused by my `core.autocrlf` settings.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
`0.7.7`

* Docker version ( Full output from: `docker version` ):
n/a

* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?
n/a

* Operating System and version (e.g. Linux, Windows, MacOS):
Windows 10

* Link to your project or a code example to reproduce issue:
n/a

### PR DESCRIPTION
**Pull request by johnmccabe**
## Description

Prevents users `.gitconfig` setting from altering template file line endings, this can cause function builds to fail when Linux `CRLF` endings are converted to Unix `LF` and vice-versa.

Also fixes an error in the `versioncontrol.core` header comment which I spotted while in there.

## Motivation and Context

- [x] I have raised an issue to propose this change (Closes #551)

## How Has This Been Tested?

- [x] **Windows 10**
  - [x] `faas template pull` with `core.autocrlf true`, line endings as set in the templates repository
  - [x] `faas template pull` with `core.autocrlf false`, line endings as set in the templates repository
  - [x] `faas new myfn --lang go` with `core.autocrlf true`, function builds
  - [x] `faas new myfn --lang go` with `core.autocrlf false`, function builds
- [x] **Linux/OSX**
  - [x] `faas template pull` with `core.autocrlf true`, line endings as set in the templates repository
  - [x] `faas template pull` with `core.autocrlf false`, line endings as set in the templates repository
  - [x] `faas new myfn --lang go` with `core.autocrlf true`, function builds
  - [x] `faas new myfn --lang go` with `core.autocrlf false`, function builds

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
@johnmccabe please reach out to someone on Slack in #contributors - call out someone by name, that seems to work best.

**Comment by alexellis** [comment]
Derek set milestone: 0.7.8

**Comment by alexellis** [comment]
When verified, I'll merge for 0.7.8. What's your ETA for checking it over on Mac?

**Comment by johnmccabe** [comment]
@alexellis looks good to merge, working as intended

**Comment by alexellis** [comment]
Cheers :+1:

**Pull request merged**
