### PR TITLE
Add token to commands

### PR DESCRIPTION
**Pull request by viveksyngh**
## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## How Has This Been Tested?

I tested all the commands changes on my cluster.

```
Test

/faas-cli-darwin deploy  -g "http://gw.viveksyngh.me:31112" --token "$TOKEN"
Deploying: stronghash.
WARNING! Communication is not secure, please consider using HTTPS. Letsencrypt.org offers free SSL/TLS certificates.

Deployed. 202 Accepted.
URL: http://gw.viveksyngh.me:31112/function/stronghash

Deploying: nodejs-echo.
WARNING! Communication is not secure, please consider using HTTPS. Letsencrypt.org offers free SSL/TLS certificates.

Deployed. 202 Accepted.
URL: http://gw.viveksyngh.me:31112/function/nodejs-echo

Deploying: shrink-image.
WARNING! Communication is not secure, please consider using HTTPS. Letsencrypt.org offers free SSL/TLS certificates.

Deployed. 202 Accepted.
URL: http://gw.viveksyngh.me:31112/function/shrink-image

Deploying: ruby-echo.
WARNING! Communication is not secure, please consider using HTTPS. Letsencrypt.org offers free SSL/TLS certificates.

Deployed. 202 Accepted.
URL: http://gw.viveksyngh.me:31112/function/ruby-echo

Deploying: url-ping.
WARNING! Communication is not secure, please consider using HTTPS. Letsencrypt.org offers free SSL/TLS certificates.

Deployed. 202 Accepted.
URL: http://gw.viveksyngh.me:31112/function/url-ping


.faas-cli-darwin deploy --name env --fprocess="env" --image="functions/alpine:latest" -g "http://gw.viveksyngh.me:31112" --token "$TOKEN"
WARNING! Communication is not secure, please consider using HTTPS. Letsencrypt.org offers free SSL/TLS certificates.

Deployed. 202 Accepted.
URL: http://gw.viveksyngh.me:31112/function/env



./faas-cli-darwin describe nodejs-echo -g "http://gw.viveksyngh.me:31112" --token "$TOKEN"
Name:                nodejs-echo
Status:              Ready
Replicas:            1
Available replicas:  1
Invocations:         0
Image:               alexellis/faas-nodejs-echo:0.1
Function process:    node index.js
URL:                 http://gw.viveksyngh.me:31112/function/nodejs-echo
Async URL:           http://gw.viveksyngh.me:31112/async-function/nodejs-echo
Labels:Annotations:%

./faas-cli-darwin remove env -g "http://gw.viveksyngh.me:31112" --token "$TOKEN"
Deleting: echo.
Removing old function.

./faas-cli-darwin secret create test-secret --from-literal=test -g "http://gw.viveksyngh.me:31112" --token "$TOKEN"
WARNING! Communication is not secure, please consider using HTTPS. Letsencrypt.org offers free SSL/TLS certificates.
Creating secret: test-secret
Created: 202 Accepted
➜  faas-cli git:(add_token_to_commands) ./faas-cli-darwin secret list -g "http://gw.viveksyngh.me:31112" --token "$TOKEN"
WARNING! Communication is not secure, please consider using HTTPS. Letsencrypt.org offers free SSL/TLS certificates.

NAME
test-secret

➜  faas-cli git:(add_token_to_commands) ./faas-cli-darwin secret update test-secret --from-literal=value  -g "http://gw.viveksyngh.me:31112" --token "$TOKEN"
WARNING! Communication is not secure, please consider using HTTPS. Letsencrypt.org offers free SSL/TLS certificates.
Updating secret: test-secret
Updated: 202 Accepted
➜  faas-cli git:(add_token_to_commands) ./faas-cli-darwin secret update test-secret --from-literal=value  -g "http://gw.viveksyngh.me:31112" --token "$TOKEN"
➜  faas-cli git:(add_token_to_commands) ./faas-cli-darwin secret remove test-secret -g "http://gw.viveksyngh.me:31112" --token "$TOKEN"
WARNING! Communication is not secure, please consider using HTTPS. Letsencrypt.org offers free SSL/TLS certificates.
Removed.. OK.
➜  faas-cli git:(add_token_to_commands) ./faas-cli-darwin secret list -g "http://gw.viveksyngh.me:31112" --token "$TOKEN"
WARNING! Communication is not secure, please consider using HTTPS. Letsencrypt.org offers free SSL/TLS certificates.
No secrets found.


 ./faas-cli-darwin store deploy nodeinfo -g "http://gw.viveksyngh.me:31112" --token "$TOKEN"
WARNING! Communication is not secure, please consider using HTTPS. Letsencrypt.org offers free SSL/TLS certificates.

Deployed. 202 Accepted.
URL: http://gw.viveksyngh.me:31112/function/nodeinfo


./faas-cli-darwin remove env -g "http://gw.viveksyngh.me:31112" --token "$TOKEN"
Deleting: env.
Removing old function.

./faas-cli-darwin version  -g "http://gw.viveksyngh.me:31112" --token "$TOKEN"
  ___                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|

CLI:
 commit:  45f1a757cd6a27be125fe1044f9f9478bebee4b7
 version: dev

Gateway
 uri:     http://gw.viveksyngh.me:31112
 version: 0.13.9
 sha:     6481b683f233c39f2f724a7a6318e445c4176b8c
 commit:  Add ca-certs to multi-arch gateways


Provider
 name:          openfaas-operator
 orchestration: kubernetes
 version:       0.9.4
 sha:           51bf99bfb695fdd27777e8b56412b1a5303a8651
```

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by LucasRoesler** [comment]
My only question on this, are the unauthenticated proxy methods still needed? Is it ok to just have one set of proxy methods and add  a comment that the caller can pass the empty string instead?  Do we foresee adding even more methods for other auth types? If we anticipate additional flows, perhaps auth should be passed as a struct (using a ptr so that the caller can pass nil for the default behavior).

**Comment by viveksyngh** [comment]
This methods are still there just to avoid updating unit tests. As per my understanding,  token will be also part of the `config.json` and we will be reading data from the config based on the gateway like we are doing for basic auth.  Once we start storing token in config, we can get rid of token argument and those methods. 

cc @alexellis

**Comment by alexellis** [comment]
Lucas thanks for that input. No auth, basic-auth and JWT are the only ones on the roadmap right now. There's been no other feature requests that I can remember. Sounds like we could do that refactoring if we got to a third method.

**Comment by LucasRoesler** [comment]
Is there an issue for integration with the `config.json`?  It would be good to link that here.  

It sounds like we have a plan, so 👍 👍

**Comment by alexellis** [comment]
Closes: #648

**Pull request merged**
